import {
  AccountHealthMetric,
  AIRecommendation,
  AmazonAccount,
  AppNotification,
  AuditLogEntry,
  ClientPerformanceReport,
  ClientSupplier,
  CustomerMessage,
  InventoryItem,
  ListingData,
  OperationalTask,
  PpcCampaign,
  PpcKeyword,
  Product,
  Promotion,
  Order,
  SyncJob,
  VeximAgencyKPIs,
  ReverseLogisticsItem,
  DemurrageTrackingRecord,
  FbaCapacityUsage,
  EtaDeviationAlert,
  SpApiQueueStatus,
} from './types'

export const mockClients: ClientSupplier[] = [
  {
    id: 'client-vina-01',
    name: 'Vinacacao Organics',
    companyName: 'Công ty Cổ phần Vinacacao Việt Nam',
    taxCode: '0304892182',
    contactPerson: 'Nguyễn Văn Hùng (CEO)',
    email: 'hung.nguyen@vinacacao.com.vn',
    phone: '+84 908 123 456',
    province: 'Bến Tre / TP.HCM',
    category: 'Grocery & Gourmet Food',
    serviceTier: 'AMAZON_GROWTH',
    joinedAt: '2025-11-15',
    amazonSellerId: 'A2VN94KAKL90US',
    amazonStoreName: 'Vinacacao USA Direct',
    connectionStatus: 'CONNECTED',
    avatarUrl: '/placeholder.svg',
    activeSkuCount: 12,
    monthlyRevenue: 68420,
    growthRate: 18.4,
    readinessAverage: 92,
  },
  {
    id: 'client-anan-02',
    name: 'An An Herbal Incense',
    companyName: 'Công ty TNHH Thảo Mộc An An',
    taxCode: '2901928374',
    contactPerson: 'Trần Thị Thu Thảo (Founder)',
    email: 'thao.tran@ananherbal.vn',
    phone: '+84 912 345 678',
    province: 'Hà Tĩnh',
    category: 'Home & Kitchen / Aromatherapy',
    serviceTier: 'AMAZON_OPERATIONS',
    joinedAt: '2026-02-10',
    amazonSellerId: 'A39XLM9812ZZUS',
    amazonStoreName: 'An An Natural Aromatics',
    connectionStatus: 'CONNECTED',
    avatarUrl: '/placeholder.svg',
    activeSkuCount: 8,
    monthlyRevenue: 34150,
    growthRate: 24.2,
    readinessAverage: 88,
  },
  {
    id: 'client-lotus-03',
    name: 'Lotus Craft Vietnam',
    companyName: 'Hợp tác xã Mây Tre Đan Sen Việt',
    taxCode: '0109283746',
    contactPerson: 'Lê Hoàng Nam (GĐ Kinh Doanh)',
    email: 'nam.le@lotuscraft.vn',
    phone: '+84 983 222 333',
    province: 'Hà Nội / Ninh Bình',
    category: 'Kitchen & Dining / Eco Home',
    serviceTier: 'AMAZON_OPERATIONS',
    joinedAt: '2026-04-01',
    amazonSellerId: 'A18BBN4545LKUS',
    amazonStoreName: 'Lotus Craft Eco Kitchen',
    connectionStatus: 'CONNECTED',
    avatarUrl: '/placeholder.svg',
    activeSkuCount: 15,
    monthlyRevenue: 28900,
    growthRate: 12.8,
    readinessAverage: 81,
  },
  {
    id: 'client-highlands-04',
    name: 'Highlands Cashew Co.',
    companyName: 'Công ty TNHH Chế Biến Hạt Tây Nguyên',
    taxCode: '3700984512',
    contactPerson: 'Phạm Minh Đức (Xuất Khẩu)',
    email: 'duc.pham@highlandscashew.com',
    phone: '+84 903 888 999',
    province: 'Bình Phước / Đắk Lắk',
    category: 'Grocery & Gourmet Food',
    serviceTier: 'AMAZON_LAUNCH',
    joinedAt: '2026-07-20',
    amazonSellerId: 'A2HIGH992811US',
    amazonStoreName: 'Highlands Cashew US Store',
    connectionStatus: 'CONNECTED',
    avatarUrl: '/placeholder.svg',
    activeSkuCount: 5,
    monthlyRevenue: 14200,
    growthRate: 35.0,
    readinessAverage: 76,
  },
  {
    id: 'client-tanviet-05',
    name: 'Tan Viet Woodcraft',
    companyName: 'Công ty Cổ phần Chế biến Gỗ Tân Việt',
    taxCode: '3601283940',
    contactPerson: 'Đỗ Quốc Việt (Phó TGĐ)',
    email: 'viet.do@tanvietwood.vn',
    phone: '+84 945 666 777',
    province: 'Đồng Nai / Bình Dương',
    category: 'Kitchen & Dining / Furniture',
    serviceTier: 'AMAZON_AUDIT',
    joinedAt: '2026-08-15',
    amazonSellerId: 'A4WOOD382910US',
    amazonStoreName: 'Tan Viet Teak Living',
    connectionStatus: 'NEEDS_REAUTH',
    avatarUrl: '/placeholder.svg',
    activeSkuCount: 6,
    monthlyRevenue: 8500,
    growthRate: 6.5,
    readinessAverage: 62,
  },
]

export const mockAmazonAccounts: AmazonAccount[] = [
  {
    id: 'acc-vina-01',
    clientId: 'client-vina-01',
    sellerId: 'A2VN94KAKL90US',
    storeName: 'Vinacacao USA Direct',
    marketplaceId: 'ATVPDKIKX0DER',
    marketplaceName: 'Amazon.com (US)',
    region: 'US',
    authStatus: 'AUTHORIZED',
    tokenExpiry: '2027-02-14T00:00:00Z',
    lastSyncTime: '4 phút trước',
    syncStatus: 'SUCCESS',
    apiQuotaUsage: 22.4,
    activeListingsCount: 12,
    accountHealthRating: 288, // Healthy (200-1000 scale)
  },
  {
    id: 'acc-anan-02',
    clientId: 'client-anan-02',
    sellerId: 'A39XLM9812ZZUS',
    storeName: 'An An Natural Aromatics',
    marketplaceId: 'ATVPDKIKX0DER',
    marketplaceName: 'Amazon.com (US)',
    region: 'US',
    authStatus: 'AUTHORIZED',
    tokenExpiry: '2027-04-10T00:00:00Z',
    lastSyncTime: '12 phút trước',
    syncStatus: 'SUCCESS',
    apiQuotaUsage: 18.1,
    activeListingsCount: 8,
    accountHealthRating: 275,
  },
]

export const mockProducts: Product[] = [
  {
    id: 'prod-vina-01',
    clientId: 'client-vina-01',
    sku: 'VXM-COCOA-70DK',
    asin: 'B0DC89X102',
    fnsku: 'X00389102A',
    upc: '893601234001',
    title: 'Vinacacao Pure Single Origin 70% Dark Chocolate Bar (Ben Tre, Vietnam) — 3.5oz Pack of 4',
    brand: 'Vinacacao',
    category: 'Grocery & Gourmet Food',
    subCategory: 'Candy & Chocolate Bars',
    mainImage: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=500&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1511381939415-e44015466834?w=500&auto=format&fit=crop&q=80',
    ],
    price: 24.99,
    cogs: 6.2,
    fbaFeeEstimated: 4.85,
    referralFeeEstimated: 3.75, // 15%
    estimatedMargin: 40.8, // percentage net profit
    weightLbs: 0.95,
    dimensionsInches: { length: 7.2, width: 3.6, height: 1.8 },
    status: 'ACTIVE',
    readinessScore: {
      overall: 94,
      productInfo: 98,
      listingQuality: 92,
      mediaAssets: 95,
      keywordCoverage: 90,
      pricingCompetitiveness: 94,
      complianceScore: 98,
      documentationScore: 95,
      blockersCount: 0,
      canLaunch: true,
      recommendations: [
        'A+ Content video module có thể tăng CVR thêm ~3.2%',
        'Thêm backend keyword "vietnamese gourmet chocolate gifts"',
      ],
    },
    documents: [
      {
        id: 'doc-01',
        title: 'FDA Food Facility Registration Certificate 2026',
        type: 'FDA_REGISTRATION',
        fileName: 'FDA_Vinacacao_Facility_Reg_2026.pdf',
        fileSize: '1.4 MB',
        fileUrl: '#',
        uploadDate: '2026-01-10',
        status: 'VERIFIED',
        extractedData: {
          manufacturer: 'Vinacacao Corp, Ben Tre Facility',
          countryOfOrigin: 'Vietnam',
          certNumber: 'FDA-19382019482',
          expiryDate: '2027-12-31',
        },
      },
      {
        id: 'doc-02',
        title: 'Certificate of Analysis (COA) - Heavy Metals & Microbiological',
        type: 'COA',
        fileName: 'COA_Batch_BT2026_DarkChoc.pdf',
        fileSize: '2.8 MB',
        fileUrl: '#',
        uploadDate: '2026-03-02',
        status: 'VERIFIED',
        extractedData: {
          productName: '70% Dark Chocolate Bar',
          ingredients: ['Cocoa mass', 'Cane sugar', 'Cocoa butter'],
        },
      },
      {
        id: 'doc-03',
        title: 'USDA Organic Seal & Non-GMO Verification',
        type: 'USDA_ORGANIC',
        fileName: 'USDA_Organic_Cert_ControlUnion.pdf',
        fileSize: '890 KB',
        fileUrl: '#',
        uploadDate: '2026-02-14',
        status: 'VERIFIED',
      },
    ],
    complianceIssues: [],
    createdAt: '2025-11-20',
    updatedAt: '2026-09-06',
  },
  {
    id: 'prod-vina-02',
    clientId: 'client-vina-01',
    sku: 'VXM-COCOA-PWD500',
    asin: 'B0DD34Y205',
    fnsku: 'X00490219B',
    upc: '893601234002',
    title: 'Vinacacao Premium 100% Pure Cocoa Powder for Baking & Smoothies — 17.6oz (500g)',
    brand: 'Vinacacao',
    category: 'Grocery & Gourmet Food',
    subCategory: 'Cocoa Powder',
    mainImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=80',
    galleryImages: [
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&auto=format&fit=crop&q=80',
    ],
    price: 16.99,
    cogs: 3.8,
    fbaFeeEstimated: 3.95,
    referralFeeEstimated: 2.55,
    estimatedMargin: 39.4,
    weightLbs: 1.18,
    dimensionsInches: { length: 8.5, width: 5.5, height: 2.2 },
    status: 'ACTIVE',
    readinessScore: {
      overall: 89,
      productInfo: 92,
      listingQuality: 85,
      mediaAssets: 88,
      keywordCoverage: 84,
      pricingCompetitiveness: 92,
      complianceScore: 96,
      documentationScore: 90,
      blockersCount: 0,
      canLaunch: true,
      recommendations: ['Tối ưu Bullet Point 2 để nhấn mạnh độ mịn 22-24% fat content.'],
    },
    documents: [],
    complianceIssues: [],
    createdAt: '2025-12-05',
    updatedAt: '2026-09-05',
  },
  {
    id: 'prod-anan-01',
    clientId: 'client-anan-02',
    sku: 'VXM-INC-AGAR100',
    asin: 'B0EE89A901',
    fnsku: 'X00551122C',
    upc: '893809112001',
    title: 'An An Natural Vietnamese Agarwood Incense Sticks (Oud) for Meditation & Yoga — 100 Sticks, 8.5 Inch',
    brand: 'An An Herbal',
    category: 'Home & Kitchen',
    subCategory: 'Incense Sticks',
    mainImage: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500&auto=format&fit=crop&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=500&auto=format&fit=crop&q=80'],
    price: 19.99,
    cogs: 3.1,
    fbaFeeEstimated: 3.45,
    referralFeeEstimated: 3.0,
    estimatedMargin: 52.2,
    weightLbs: 0.45,
    dimensionsInches: { length: 9.0, width: 2.2, height: 1.5 },
    status: 'ACTIVE',
    readinessScore: {
      overall: 91,
      productInfo: 95,
      listingQuality: 88,
      mediaAssets: 90,
      keywordCoverage: 92,
      pricingCompetitiveness: 90,
      complianceScore: 92,
      documentationScore: 90,
      blockersCount: 0,
      canLaunch: true,
      recommendations: ['Bổ sung so sánh với hóa chất hương liệu nhân tạo thông thường.'],
    },
    documents: [],
    complianceIssues: [],
    createdAt: '2026-02-12',
    updatedAt: '2026-09-06',
  },
  {
    id: 'prod-lotus-01',
    clientId: 'client-lotus-03',
    sku: 'VXM-BAMB-STR100',
    asin: 'B0FF12C345',
    fnsku: 'X00662233D',
    upc: '893902837001',
    title: 'Lotus Craft Natural Vietnamese Bamboo Drinking Straws Reusable Set of 12 with Cleaning Brush & Pouch',
    brand: 'Lotus Craft',
    category: 'Kitchen & Dining',
    subCategory: 'Disposable & Reusable Straws',
    mainImage: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&auto=format&fit=crop&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=500&auto=format&fit=crop&q=80'],
    price: 14.5,
    cogs: 2.2,
    fbaFeeEstimated: 3.15,
    referralFeeEstimated: 2.18,
    estimatedMargin: 48.1,
    weightLbs: 0.38,
    dimensionsInches: { length: 8.8, width: 3.0, height: 1.2 },
    status: 'ACTIVE',
    readinessScore: {
      overall: 82,
      productInfo: 85,
      listingQuality: 78,
      mediaAssets: 80,
      keywordCoverage: 82,
      pricingCompetitiveness: 85,
      complianceScore: 88,
      documentationScore: 80,
      blockersCount: 0,
      canLaunch: true,
      recommendations: ['Tiêu đề thiếu từ khóa search volume cao "dishwasher safe organic straws".'],
    },
    documents: [],
    complianceIssues: [],
    createdAt: '2026-04-05',
    updatedAt: '2026-09-04',
  },
  {
    id: 'prod-highlands-01',
    clientId: 'client-highlands-04',
    sku: 'VXM-CASH-ROAST500',
    asin: 'B0GG78D567',
    fnsku: 'X00773344E',
    upc: '893701928001',
    title: 'Highlands Roasted Vietnamese Cashews with Sea Salt & Chili Flakes — W240 Jumbo Size, 16oz Resealable Bag',
    brand: 'Highlands Cashew',
    category: 'Grocery & Gourmet Food',
    subCategory: 'Cashews',
    mainImage: 'https://images.unsplash.com/photo-1509912760295-8854c86e0a96?w=500&auto=format&fit=crop&q=80',
    galleryImages: ['https://images.unsplash.com/photo-1509912760295-8854c86e0a96?w=500&auto=format&fit=crop&q=80'],
    price: 18.5,
    cogs: 4.5,
    fbaFeeEstimated: 3.85,
    referralFeeEstimated: 2.78,
    estimatedMargin: 39.8,
    weightLbs: 1.08,
    dimensionsInches: { length: 8.2, width: 5.5, height: 2.5 },
    status: 'COMPLIANCE_REVIEW',
    readinessScore: {
      overall: 68,
      productInfo: 80,
      listingQuality: 65,
      mediaAssets: 70,
      keywordCoverage: 62,
      pricingCompetitiveness: 75,
      complianceScore: 58,
      documentationScore: 60,
      blockersCount: 2,
      canLaunch: false,
      recommendations: [
        'BLOCKER: Cần bổ sung bảng Nutrition Facts chuẩn FDA 2026 (Daily Value % và Allergen Warning: Tree Nuts).',
        'BLOCKER: Chưa có giấy PhytoSanitary kiểm dịch thực vật từ Bộ NN&PTNT trước khi xuất sang cảng Long Beach.',
      ],
    },
    documents: [],
    complianceIssues: [
      {
        id: 'comp-01',
        code: 'FDA-ALLERGEN-LABEL',
        title: 'Thiếu cảnh báo dị ứng hạt "Contains: Cashews (Tree Nuts)" chuẩn FALCPA',
        severity: 'CRITICAL_BLOCK',
        category: 'FDA',
        description: 'Bao bì xuất khẩu hiện tại chưa in rõ cảnh báo Major Food Allergens theo quy định FDA Hoa Kỳ.',
        remedy: 'Yêu cầu xưởng in lại nhãn phụ dán đè (sticker overlay) hoặc in bao bì mới.',
        isResolved: false,
      },
      {
        id: 'comp-02',
        code: 'USDA-PHYTO-01',
        title: 'Thiếu Phytosanitary Certificate cho lô hàng nông sản chưa qua chế biến nhiệt cao',
        severity: 'CRITICAL_BLOCK',
        category: 'HAZMAT',
        description: 'Amazon và Hải quan Mỹ yêu cầu giấy chứng nhận kiểm dịch thực vật đối với nông sản nhập khẩu.',
        remedy: 'Đội Compliance Vexim hỗ trợ nộp hồ sơ xin giấy chứng nhận tại Chi cục Kiểm dịch thực vật Vùng II.',
        isResolved: false,
      },
    ],
    createdAt: '2026-07-22',
    updatedAt: '2026-09-06',
  },
]

export const mockListings: ListingData[] = [
  {
    id: 'list-01',
    productId: 'prod-vina-01',
    sku: 'VXM-COCOA-70DK',
    asin: 'B0DC89X102',
    title: 'Vinacacao Pure Single Origin 70% Dark Chocolate Bar (Ben Tre, Vietnam) — 3.5oz Pack of 4',
    bulletPoints: [
      'AUTHENTIC VIETNAMESE SINGLE ORIGIN: Crafted exclusively with Trinitario cocoa beans harvested in the fertile Mekong Delta terroir of Ben Tre, Vietnam.',
      '70% PURE RICH COCOA: Intense bittersweet flavor profile with natural fruity notes of dried plum, citrus undertones, and velvet finish without artificial flavorings.',
      'USDA ORGANIC & NON-GMO CERTIFIED: Ethically sourced through direct trade with local Vietnamese smallholder farmers ensuring fair wages and sustainable agroforestry.',
      'CLEAN INGREDIENTS: Only 3 pure ingredients — Organic Cocoa Mass, Organic Cane Sugar, and Pure Cocoa Butter. Gluten-free, Vegan, and Soy-Lecithin Free.',
      'PREMIUM GIFT PACKAGING: Includes four individually wrapped 3.5oz bars in airtight protective foil packaging, perfect for foodies, wine pairing, and luxury gifting.',
    ],
    description:
      'Discover the rare and exquisite taste of Vietnamese chocolate with Vinacacao. Our single origin 70% dark chocolate is harvested in Ben Tre, known as the kingdom of coconut and cocoa along the Mekong Delta.',
    backendSearchTerms:
      'vietnamese chocolate dark chocolate gift pack organic cocoa single origin chocolate gourmet baking vegan dark chocolate bars non gmo healthy snacks',
    price: 24.99,
    currency: 'USD',
    lastOptimizedAt: '2026-08-28',
    currentScore: {
      overall: 88,
      titleScore: 84,
      bulletScore: 92,
      keywordScore: 86,
      contentScore: 90,
      conversionPotential: 'A',
      complianceRisk: 'LOW',
      strengths: [
        'Bullet points nêu rõ chứng nhận USDA Organic, Non-GMO và thành phần sạch 3 nguyên liệu.',
        'Độ dài tiêu đề tối ưu 138 ký tự, thân thiện mobile shopping.',
      ],
      weaknesses: [
        'Tiêu đề còn thiếu từ khóa high-intent "Gourmet Gift Box".',
        'Backend keywords chưa tận dụng hết 249 bytes (hiện dùng 184 bytes).',
      ],
    },
    aiOptimizationDraft: {
      id: 'draft-vina-01',
      title:
        'Vinacacao Single Origin 70% Dark Chocolate Bars from Vietnam (Ben Tre Mekong Delta) — Gourmet Organic Vegan Gift Pack, 3.5oz (Pack of 4)',
      bulletPoints: [
        'AUTHENTIC SINGLE-ORIGIN VIETNAMESE COCOA: Hand-harvested Trinitario beans from Ben Tre Mekong Delta terroir, celebrated worldwide for delicate fruit acidity and deep cocoa aroma.',
        'RICH 70% BITTERSWEET BALANCE: Velvety mouthfeel with subtle notes of dried plum and honeyed citrus; no artificial additives, preservatives, or palm oil.',
        'CERTIFIED ORGANIC & DIRECT TRADE: USDA Organic, Non-GMO Verified, and fairly traded directly with multi-generational Vietnamese cocoa farming families.',
        '100% VEGAN & ALLERGEN-FRIENDLY: Made with just 3 pure ingredients (Cocoa Mass, Cane Sugar, Cocoa Butter). Free from Dairy, Gluten, Soy Lecithin, and Peanuts.',
        'LUXURY GIFT READY: Beautifully packaged set of 4 individually sealed bars, ideal for dark chocolate connoisseurs, espresso/wine pairing, and anniversary gifts.',
      ],
      description:
        'Experience the pinnacle of Southeast Asian craft chocolate. Vinacacao partners directly with sustainable farms in Vietnam to craft unforgettable dark chocolate with zero compromises.',
      backendSearchTerms:
        'vietnam dark chocolate bars gourmet gift basket organic vegan artisan craft chocolate keto friendly dairy free candy premium holiday gifts wine pairing',
      targetKeywords: ['artisan dark chocolate', 'vietnamese gourmet gifts', 'organic chocolate pack'],
      projectedScore: 96,
      reasoning:
        'Bổ sung cụm từ khóa có tỷ lệ chuyển đổi cao "Gourmet Organic Vegan Gift Pack" vào tiêu đề; tăng cường chứng chỉ trong Bullet #4; lấp đầy 248 bytes search terms.',
      status: 'WAITING_APPROVAL',
    },
  },
  {
    id: 'list-02',
    productId: 'prod-anan-01',
    sku: 'VXM-INC-AGAR100',
    asin: 'B0EE89A901',
    title: 'An An Natural Vietnamese Agarwood Incense Sticks (Oud) for Meditation & Yoga — 100 Sticks, 8.5 Inch',
    bulletPoints: [
      'GENUINE WILD-GRADE AGARWOOD: Sourced from sustainable aquilaria trees in Ha Tinh, Vietnam.',
      '100% CHEMICAL FREE: Made from pure agarwood powder and natural litsea glutinosa binder.',
      'CALMING & PURIFYING: Deep, warm, sweet woody aroma that calms the mind during meditation.',
      'CLEAN BURNING: Minimal smoke with approximately 40 minutes burn time per stick.',
      'MONEY BACK GUARANTEE: Handcrafted with respect for Vietnamese traditional herbal heritage.',
    ],
    description: 'Purify your living sanctuary with authentic Vietnamese Agarwood Incense from An An.',
    backendSearchTerms:
      'agarwood incense oud sticks natural organic meditation incense non toxic yoga incense calming aroma therapy',
    price: 19.99,
    currency: 'USD',
    currentScore: {
      overall: 76,
      titleScore: 78,
      bulletScore: 72,
      keywordScore: 75,
      contentScore: 80,
      conversionPotential: 'B',
      complianceRisk: 'LOW',
      strengths: ['Thông điệp tự nhiên 100% không hóa chất rõ ràng.'],
      weaknesses: [
        'Bullet #2 quá ngắn và thiếu số liệu kiểm định khói an toàn.',
        'Thiếu so sánh trực tiếp với hương nhân tạo tẩm tinh dầu rẻ tiền.',
      ],
    },
  },
]

export const mockInventory: InventoryItem[] = [
  {
    id: 'inv-01',
    clientId: 'client-vina-01',
    sku: 'VXM-COCOA-70DK',
    asin: 'B0DC89X102',
    title: 'Vinacacao 70% Dark Chocolate Bar (Pack of 4)',
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=100&auto=format&fit=crop&q=80',
    fbaAvailable: 168,
    fbaReserved: 24,
    fbaInbound: 400, // In transit from Vietnam to Amazon LGB8 warehouse
    dailyVelocity7d: 14.2,
    dailyVelocity30d: 12.8,
    daysOfSupply: 11.8, // 168 / 14.2 = 11.8 days -> CRITICAL!
    supplierLeadTimeDays: 32, // Factory prep 7d + Sea freight 21d + FC receiving 4d
    reorderPointDays: 35,
    reorderPointUnits: 500,
    riskLevel: 'CRITICAL',
    inventoryValueUsd: 1041.6,
    unitCostUsd: 6.2,
    recommendedReorderQty: 1200,
    estimatedStockoutDate: '2026-09-19',
    lastRestockedDate: '2026-08-10',
  },
  {
    id: 'inv-02',
    clientId: 'client-vina-02',
    sku: 'VXM-COCOA-PWD500',
    asin: 'B0DD34Y205',
    title: 'Vinacacao 100% Pure Cocoa Powder 500g',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=100&auto=format&fit=crop&q=80',
    fbaAvailable: 340,
    fbaReserved: 18,
    fbaInbound: 250,
    dailyVelocity7d: 18.5,
    dailyVelocity30d: 16.0,
    daysOfSupply: 18.4, // HIGH RISK
    supplierLeadTimeDays: 30,
    reorderPointDays: 32,
    reorderPointUnits: 580,
    riskLevel: 'HIGH',
    inventoryValueUsd: 1292.0,
    unitCostUsd: 3.8,
    recommendedReorderQty: 800,
    estimatedStockoutDate: '2026-09-26',
    lastRestockedDate: '2026-08-18',
  },
  {
    id: 'inv-03',
    clientId: 'client-anan-01',
    sku: 'VXM-INC-AGAR100',
    asin: 'B0EE89A901',
    title: 'An An Natural Agarwood Incense 100s',
    imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=100&auto=format&fit=crop&q=80',
    fbaAvailable: 280,
    fbaReserved: 12,
    fbaInbound: 300,
    dailyVelocity7d: 11.2,
    dailyVelocity30d: 9.5,
    daysOfSupply: 25.0, // MEDIUM RISK
    supplierLeadTimeDays: 28,
    reorderPointDays: 30,
    reorderPointUnits: 340,
    riskLevel: 'MEDIUM',
    inventoryValueUsd: 868.0,
    unitCostUsd: 3.1,
    recommendedReorderQty: 600,
    estimatedStockoutDate: '2026-10-02',
    lastRestockedDate: '2026-08-25',
  },
  {
    id: 'inv-04',
    clientId: 'client-lotus-01',
    sku: 'VXM-BAMB-STR100',
    asin: 'B0FF12C345',
    title: 'Lotus Craft Bamboo Straws Set of 12',
    imageUrl: 'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?w=100&auto=format&fit=crop&q=80',
    fbaAvailable: 620,
    fbaReserved: 30,
    fbaInbound: 500,
    dailyVelocity7d: 13.5,
    dailyVelocity30d: 14.1,
    daysOfSupply: 45.9, // HEALTHY
    supplierLeadTimeDays: 30,
    reorderPointDays: 30,
    reorderPointUnits: 420,
    riskLevel: 'HEALTHY',
    inventoryValueUsd: 1364.0,
    unitCostUsd: 2.2,
    recommendedReorderQty: 0,
    estimatedStockoutDate: null,
    lastRestockedDate: '2026-08-29',
  },
  {
    id: 'inv-05',
    clientId: 'client-highlands-01',
    sku: 'VXM-CASH-ROAST500',
    asin: 'B0GG78D567',
    title: 'Highlands Roasted Cashews Sea Salt 16oz',
    imageUrl: 'https://images.unsplash.com/photo-1509912760295-8854c86e0a96?w=100&auto=format&fit=crop&q=80',
    fbaAvailable: 85,
    fbaReserved: 10,
    fbaInbound: 0,
    dailyVelocity7d: 6.8,
    dailyVelocity30d: 5.5,
    daysOfSupply: 12.5,
    supplierLeadTimeDays: 35,
    reorderPointDays: 35,
    reorderPointUnits: 240,
    riskLevel: 'CRITICAL',
    inventoryValueUsd: 382.5,
    unitCostUsd: 4.5,
    recommendedReorderQty: 500,
    estimatedStockoutDate: '2026-09-20',
    lastRestockedDate: '2026-08-01',
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ord-114-9028121-1928301',
    amazonOrderId: '114-9028121-1928301',
    clientId: 'client-vina-01',
    purchaseDate: '2026-09-07T08:42:10Z',
    orderStatus: 'UNSHIPPED',
    fulfillmentChannel: 'FBA',
    salesChannel: 'Amazon.com',
    orderTotal: 49.98,
    itemCount: 2,
    customerCity: 'Los Angeles',
    customerState: 'CA',
    customerPostalCode: '90012',
    carrier: 'Amazon Logistics',
    trackingNumber: 'TBA309182390192',
    items: [
      {
        sku: 'VXM-COCOA-70DK',
        asin: 'B0DC89X102',
        title: 'Vinacacao Single Origin 70% Dark Chocolate Bar (Pack of 4)',
        quantity: 2,
        unitPrice: 24.99,
        itemTotal: 49.98,
      },
    ],
    hasProblem: false,
  },
  {
    id: 'ord-112-7819283-9182391',
    amazonOrderId: '112-7819283-9182391',
    clientId: 'client-vina-01',
    purchaseDate: '2026-09-07T07:15:22Z',
    orderStatus: 'SHIPPED',
    fulfillmentChannel: 'FBA',
    salesChannel: 'Amazon.com',
    orderTotal: 24.99,
    itemCount: 1,
    customerCity: 'Austin',
    customerState: 'TX',
    customerPostalCode: '78701',
    carrier: 'UPS',
    trackingNumber: '1Z9999999999999999',
    items: [
      {
        sku: 'VXM-COCOA-70DK',
        asin: 'B0DC89X102',
        title: 'Vinacacao Single Origin 70% Dark Chocolate Bar (Pack of 4)',
        quantity: 1,
        unitPrice: 24.99,
        itemTotal: 24.99,
      },
    ],
    hasProblem: false,
  },
  {
    id: 'ord-111-3498192-8172938',
    amazonOrderId: '111-3498192-8172938',
    clientId: 'client-anan-02',
    purchaseDate: '2026-09-07T06:30:11Z',
    orderStatus: 'DELIVERED',
    fulfillmentChannel: 'FBA',
    salesChannel: 'Amazon.com',
    orderTotal: 39.98,
    itemCount: 2,
    customerCity: 'Seattle',
    customerState: 'WA',
    customerPostalCode: '98101',
    carrier: 'USPS',
    trackingNumber: '9400100000000000000000',
    items: [
      {
        sku: 'VXM-INC-AGAR100',
        asin: 'B0EE89A901',
        title: 'An An Natural Vietnamese Agarwood Incense Sticks 100s',
        quantity: 2,
        unitPrice: 19.99,
        itemTotal: 39.98,
      },
    ],
    hasProblem: false,
  },
  {
    id: 'ord-113-5819284-0192834',
    amazonOrderId: '113-5819284-0192834',
    clientId: 'client-vina-01',
    purchaseDate: '2026-09-06T19:40:00Z',
    orderStatus: 'PENDING',
    fulfillmentChannel: 'FBA',
    salesChannel: 'Amazon.com',
    orderTotal: 33.98,
    itemCount: 2,
    customerCity: 'Miami',
    customerState: 'FL',
    customerPostalCode: '33101',
    items: [
      {
        sku: 'VXM-COCOA-PWD500',
        asin: 'B0DD34Y205',
        title: 'Vinacacao Premium Cocoa Powder 500g',
        quantity: 2,
        unitPrice: 16.99,
        itemTotal: 33.98,
      },
    ],
    hasProblem: true,
    problemReason: 'Payment authorization pending (> 24h)',
    aiProblemDiagnosis: 'Thẻ tín dụng của người mua cần xác thực OTP từ ngân hàng phát hành. Amazon tự động gửi nhắc nhở.',
  },
  {
    id: 'ord-114-2291039-4829102',
    amazonOrderId: '114-2291039-4829102',
    clientId: 'client-lotus-03',
    purchaseDate: '2026-09-06T14:12:09Z',
    orderStatus: 'DELIVERED',
    fulfillmentChannel: 'FBA',
    salesChannel: 'Amazon.com',
    orderTotal: 14.5,
    itemCount: 1,
    customerCity: 'Chicago',
    customerState: 'IL',
    customerPostalCode: '60601',
    carrier: 'Amazon Logistics',
    trackingNumber: 'TBA940182749102',
    items: [
      {
        sku: 'VXM-BAMB-STR100',
        asin: 'B0FF12C345',
        title: 'Lotus Craft Bamboo Straws Set of 12',
        quantity: 1,
        unitPrice: 14.5,
        itemTotal: 14.5,
      },
    ],
    hasProblem: false,
  },
]

export const mockPpcCampaigns: PpcCampaign[] = [
  {
    id: 'camp-01',
    clientId: 'client-vina-01',
    campaignName: 'SP_Chocolate_Exact_Brand_HighIntent',
    type: 'SPONSORED_PRODUCTS',
    targetingType: 'MANUAL',
    status: 'ENABLED',
    dailyBudget: 45.0,
    spend7d: 284.5,
    sales7d: 1420.0,
    orders7d: 58,
    impressions7d: 18450,
    clicks7d: 242,
    ctr: 1.31,
    cpc: 1.18,
    acos: 20.04, // 20% vs target 25% -> EXCELLENT
    targetAcos: 25.0,
    tacos: 11.2,
    roas: 4.99,
  },
  {
    id: 'camp-02',
    clientId: 'client-vina-01',
    campaignName: 'SP_DarkChoc_Broad_Generic_Exploration',
    type: 'SPONSORED_PRODUCTS',
    targetingType: 'MANUAL',
    status: 'ENABLED',
    dailyBudget: 30.0,
    spend7d: 210.0,
    sales7d: 380.0,
    orders7d: 15,
    impressions7d: 29800,
    clicks7d: 310,
    ctr: 1.04,
    cpc: 0.68,
    acos: 55.26, // 55% vs target 28% -> BLEEDING!
    targetAcos: 28.0,
    tacos: 14.5,
    roas: 1.81,
  },
  {
    id: 'camp-03',
    clientId: 'client-anan-02',
    campaignName: 'SP_Agarwood_Exact_Meditation',
    type: 'SPONSORED_PRODUCTS',
    targetingType: 'MANUAL',
    status: 'ENABLED',
    dailyBudget: 25.0,
    spend7d: 148.0,
    sales7d: 680.0,
    orders7d: 34,
    impressions7d: 12400,
    clicks7d: 158,
    ctr: 1.27,
    cpc: 0.94,
    acos: 21.76,
    targetAcos: 25.0,
    tacos: 9.8,
    roas: 4.59,
  },
]

export const mockPpcKeywords: PpcKeyword[] = [
  {
    id: 'kw-01',
    campaignId: 'camp-01',
    campaignName: 'SP_Chocolate_Exact_Brand_HighIntent',
    keywordText: 'vietnamese dark chocolate',
    matchType: 'EXACT',
    bid: 1.25,
    suggestedBid: { low: 0.95, mid: 1.22, high: 1.65 },
    impressions: 4850,
    clicks: 84,
    ctr: 1.73,
    spend: 96.6,
    sales: 549.78,
    orders: 22,
    acos: 17.57, // Excellent converter
    conversionRate: 26.19,
    status: 'ENABLED',
  },
  {
    id: 'kw-02',
    campaignId: 'camp-02',
    campaignName: 'SP_DarkChoc_Broad_Generic_Exploration',
    keywordText: 'cheap dark candy bar',
    matchType: 'BROAD',
    bid: 0.85,
    suggestedBid: { low: 0.5, mid: 0.75, high: 1.1 },
    impressions: 9800,
    clicks: 110,
    ctr: 1.12,
    spend: 88.0,
    sales: 99.96,
    orders: 4,
    acos: 88.03, // Bleeding keyword!
    conversionRate: 3.63,
    status: 'ENABLED',
  },
  {
    id: 'kw-03',
    campaignId: 'camp-01',
    campaignName: 'SP_Chocolate_Exact_Brand_HighIntent',
    keywordText: 'single origin chocolate gift box',
    matchType: 'EXACT',
    bid: 1.15,
    suggestedBid: { low: 1.1, mid: 1.45, high: 2.1 },
    impressions: 2100,
    clicks: 42,
    ctr: 2.0,
    spend: 48.3,
    sales: 299.88,
    orders: 12,
    acos: 16.11,
    conversionRate: 28.57,
    status: 'ENABLED',
  },
]

export const mockPromotions: Promotion[] = [
  {
    id: 'promo-01',
    clientId: 'client-vina-01',
    name: 'Prime Autumn Gourmet Week — 15% Off Coupon',
    type: 'COUPON',
    discountValue: 15,
    discountType: 'PERCENT',
    targetSkus: ['VXM-COCOA-70DK', 'VXM-COCOA-PWD500'],
    startDate: '2026-09-01',
    endDate: '2026-09-15',
    status: 'ACTIVE',
    budget: 500,
    spend: 214,
    redemptions: 68,
    attributedSales: 2150,
    salesUpliftPercent: 34.2,
    marginImpactPercent: -4.8,
    roi: 4.8,
  },
  {
    id: 'promo-02',
    clientId: 'client-anan-02',
    name: 'Fall Equinox Wellness — Prime Exclusive Deal 10%',
    type: 'PRIME_EXCLUSIVE_DISCOUNT',
    discountValue: 10,
    discountType: 'PERCENT',
    targetSkus: ['VXM-INC-AGAR100'],
    startDate: '2026-09-18',
    endDate: '2026-09-25',
    status: 'SCHEDULED',
    budget: 350,
    spend: 0,
    redemptions: 0,
    attributedSales: 0,
    salesUpliftPercent: 0,
    marginImpactPercent: -3.2,
    roi: 0,
  },
]

export const mockCustomerMessages: CustomerMessage[] = [
  {
    id: 'msg-01',
    clientId: 'client-vina-01',
    amazonMessageId: 'amzn-msg-901823901',
    orderId: '114-9028121-1928301',
    customerName: 'Sarah Jenkins (CA, USA)',
    receivedAt: '2026-09-07T08:10:00Z',
    messageSubject: 'Inquiry about melting in hot weather transit',
    messageBody:
      'Hi, I just placed an order for the 4-pack chocolate bars. It is currently 92°F in Los Angeles. Will this be shipped with insulated ice packs to prevent melting?',
    classification: 'NORMAL_INQUIRY',
    safetyRiskDetected: false,
    aiSuggestedDraft:
      'Dear Sarah, Thank you for your order and for contacting Vinacacao! All our chocolate orders fulfilled by Amazon (FBA) are packaged in climate-controlled protective materials to maintain quality during summer transit. If your order arrives with any signs of heat damage, please let us know immediately and we will promptly send a replacement or full refund. Have a wonderful day!',
    status: 'PENDING_APPROVAL',
  },
  {
    id: 'msg-02',
    clientId: 'client-anan-02',
    amazonMessageId: 'amzn-msg-781920192',
    orderId: '111-3498192-8172938',
    customerName: 'Michael Thornton (WA, USA)',
    receivedAt: '2026-09-07T06:45:00Z',
    messageSubject: 'Question regarding stick burn time',
    messageBody:
      'Hello, I burned one stick yesterday in my yoga room. It lasted about 45 minutes and smelled amazing. Just wondering if you also make shorter cones or backflow incense?',
    classification: 'NORMAL_INQUIRY',
    safetyRiskDetected: false,
    aiSuggestedDraft:
      'Dear Michael, Thank you so much for your kind feedback! We are thrilled that you loved the authentic Vietnamese agarwood scent for your yoga practice. We are currently preparing to launch our handcrafted Agarwood Cones and Backflow collection on Amazon US next month. We would love to share an update with you once available!',
    status: 'PENDING_APPROVAL',
  },
  {
    id: 'msg-03',
    clientId: 'client-lotus-03',
    amazonMessageId: 'amzn-msg-381920481',
    orderId: '114-2291039-4829102',
    customerName: 'Amanda R. (IL, USA)',
    receivedAt: '2026-09-06T20:15:00Z',
    messageSubject: 'CRITICAL: Child minor lip irritation inquiry & splinters claim',
    messageBody:
      'WARNING: My 6 year old daughter used one of the bamboo straws from the pack and noticed rough splintering near the rim that caused a minor lip scratch. Please check your quality control or I will report to CPSC/FDA!',
    classification: 'SAFETY_CRITICAL',
    safetyRiskDetected: true,
    safetyKeywords: ['lip scratch', 'splinters', 'injury', 'CPSC/FDA', 'child'],
    aiSuggestedDraft:
      'CRITICAL SAFETY ESCALATION: Auto-response strictly blocked by Vexim AI Compliance Guard. High risk product liability keyword detected. Required Human Action: Operations Manager must immediately inspect batch QA inspection records, isolate SKU VXM-BAMB-STR100 lot #LC26-04, and initiate customer care phone/direct response protocol within 2 hours.',
    status: 'ESCALATED_TO_HUMAN',
  },
]

export const mockAccountHealth: AccountHealthMetric = {
  overallScore: 288, // 200-1000 Amazon scale (Healthy: 200+, At Risk: 100-199, Critical: 0-99)
  status: 'HEALTHY',
  orderDefectRate: { value: 0.18, target: 1.0, status: 'GOOD' }, // 0.18% vs < 1.0%
  lateShipmentRate: { value: 0.45, target: 4.0, status: 'GOOD' }, // 0.45% vs < 4.0%
  validTrackingRate: { value: 99.4, target: 95.0, status: 'GOOD' }, // 99.4% vs > 95.0%
  policyComplianceIssues: [
    {
      id: 'issue-01',
      type: 'LISTING_POLICY',
      title: 'Potential high-intent keyword discrepancy on SKU VXM-COCOA-PWD500',
      severity: 'LOW',
      detectedAt: '2026-09-04',
      deadline: '2026-09-18',
      status: 'OPEN',
      affectedAsin: 'B0DD34Y205',
      recommendedAction:
        'Loại bỏ từ khóa nhạy cảm "cure chocolate craving" khỏi search terms để đảm bảo tuân thủ Amazon Medical Claims policy.',
    },
    {
      id: 'issue-02',
      type: 'FOOD_SAFETY',
      title: 'FDA Biennial Facility Registration Verification Request',
      severity: 'MEDIUM',
      detectedAt: '2026-09-01',
      deadline: '2026-09-25',
      status: 'APPEAL_SUBMITTED',
      affectedAsin: 'ALL_GROCERY_ASINS',
      recommendedAction:
        'Hồ sơ FDA 2026 đã được upload lên Seller Central Account Health Portal. Đang đợi Amazon SP Compliance xác nhận.',
    },
  ],
  openCasesCount: 2,
}

export const mockRecommendations: AIRecommendation[] = [
  {
    id: 'rec-01',
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    amazonAccountId: 'acc-vina-01',
    agentType: 'INVENTORY',
    entityType: 'INVENTORY',
    entityId: 'inv-01',
    entityIdentifier: 'VXM-COCOA-70DK (B0DC89X102)',
    title: 'Cảnh báo hết hàng FBA trong 11.8 ngày — Cần phê duyệt PO bổ sung 1,200 units',
    description:
      'Tốc độ bán trung bình 7 ngày qua đạt 14.2 units/ngày (tăng 22%). Tồn kho FBA hiện tại chỉ còn 168 units. Thời gian sản xuất và vận chuyển biển từ cảng Cát Lái sang Long Beach mất 32 ngày.',
    reason:
      'Nếu không tạo đơn đặt hàng ngay hôm nay, sản phẩm sẽ đứt hàng vào ngày 19/09/2026, làm mất thứ hạng Best Seller Rank (BSR) từ #42 xuống >#200.',
    confidenceScore: 96,
    priority: 'CRITICAL',
    riskLevel: 'HIGH',
    proposedAction: 'Tạo Task sản xuất khẩn cấp 1,200 units tại xưởng Bến Tre và book chuyến bay Air Express 300 units.',
    actionData: {
      sku: 'VXM-COCOA-70DK',
      recommendedSeaUnits: 900,
      recommendedAirExpressUnits: 300,
      estimatedProductionCostUsd: 7440,
      leadTimeDays: 32,
    },
    beforeState: { availableUnits: 168, daysOfSupply: 11.8, stockoutRisk: 'CRITICAL' },
    proposedState: { addedUnits: 1200, targetDaysOfSupply: 65, stockoutRisk: 'MITIGATED' },
    expectedImpact: 'Ngăn chặn thiệt hại doanh thu dự kiến ~$8,850 và bảo vệ Organic Ranking BSR.',
    requiresExplicitApproval: true,
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-07T06:00:00Z',
  },
  {
    id: 'rec-02',
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    amazonAccountId: 'acc-vina-01',
    agentType: 'PPC',
    entityType: 'KEYWORD',
    entityId: 'kw-02',
    entityIdentifier: 'SP_DarkChoc_Broad_Generic (cheap dark candy bar)',
    title: 'Giảm 35% bid từ khóa lãng phí ngân sách (ACOS 88.03% vs Target 28%)',
    description:
      'Từ khóa match broad "cheap dark candy bar" đã tiêu $88.00 trong 7 ngày nhưng chỉ mang lại $99.96 doanh thu (ACOS 88.03%), kéo giảm tỷ suất lợi nhuận chiến dịch.',
    reason:
      'Khách tìm kiếm từ khóa "cheap" có intent mua kẹo giá rẻ $1-2, không phù hợp với phân khúc socola thủ công cao cấp $24.99 của Vinacacao.',
    confidenceScore: 94,
    priority: 'HIGH',
    riskLevel: 'LOW',
    proposedAction: 'Giảm bid từ $0.85 xuống $0.55 và đưa cụm từ "cheap" vào danh sách Negative Phrase Search Terms.',
    actionData: {
      campaignId: 'camp-02',
      keywordId: 'kw-02',
      currentBid: 0.85,
      newBid: 0.55,
      addNegativePhrase: 'cheap',
    },
    beforeState: { currentBid: 0.85, currentAcos: 88.03, weeklySpend: 88.0 },
    proposedState: { proposedBid: 0.55, projectedAcos: 32.0, weeklySavings: 45.0 },
    expectedImpact: 'Tiết kiệm ~$180/tháng ngân sách quảng cáo vô ích và tái phân bổ sang Exact match.',
    requiresExplicitApproval: true,
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-07T05:30:00Z',
  },
  {
    id: 'rec-03',
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    amazonAccountId: 'acc-vina-01',
    agentType: 'LISTING',
    entityType: 'LISTING',
    entityId: 'list-01',
    entityIdentifier: 'SKU VXM-COCOA-70DK (ASIN B0DC89X102)',
    title: 'Áp dụng bản tối ưu hóa Listing AI V2 — Nâng điểm chất lượng từ 88 lên 96/100',
    description:
      'AI Listing Agent đã phân tích 10 đối thủ hàng đầu trên Amazon US (Hu Chocolate, Taza Chocolate, Endangered Species) và tạo bản nháp tối ưu tiêu đề, 5 bullet points và backend search terms.',
    reason:
      'Listing hiện tại đang bỏ lỡ lượng traffic tìm kiếm từ khóa quà tặng "Gourmet Organic Vegan Gift Pack" và thiếu nhấn mạnh chứng chỉ Direct Trade.',
    confidenceScore: 92,
    priority: 'OPPORTUNITY',
    riskLevel: 'LOW',
    proposedAction: 'Phê duyệt bản nháp Listing AI và đẩy tự động lên Amazon Selling Partner API.',
    actionData: {
      listingId: 'list-01',
      draftId: 'draft-vina-01',
      targetScore: 96,
    },
    beforeState: { currentScore: 88, titleLength: 138, estimatedCVR: '11.8%' },
    proposedState: { targetScore: 96, titleLength: 178, estimatedCVR: '13.9%' },
    expectedImpact: 'Dự kiến tăng tỷ lệ chuyển đổi (CVR) thêm ~17.8%, tương đương +$2,400 doanh thu/tháng.',
    requiresExplicitApproval: true,
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-06T22:00:00Z',
  },
  {
    id: 'rec-04',
    clientId: 'client-anan-02',
    clientName: 'An An Herbal Incense',
    amazonAccountId: 'acc-anan-02',
    agentType: 'PPC',
    entityType: 'KEYWORD',
    entityId: 'kw-01-an',
    entityIdentifier: 'SP_Agarwood_Exact (natural oud meditation)',
    title: 'Tăng 12% bid từ khóa chuyển đổi cao để chiếm Top of Search (ACOS 17.5%)',
    description:
      'Từ khóa "vietnamese natural agarwood incense" có tỷ lệ chuyển đổi vượt trội 28.5%, ACOS đạt 17.5% (dưới mục tiêu 25%), nhưng tỷ lệ hiển thị Top of Search chỉ đạt 32%.',
    reason:
      'Tăng nhẹ giá thầu sẽ giúp chiếm trọn vị trí #1 tài trợ và tăng gấp đôi số đơn hàng organic kèm theo.',
    confidenceScore: 95,
    priority: 'OPPORTUNITY',
    riskLevel: 'LOW',
    proposedAction: 'Tăng bid từ $1.15 lên $1.29 và tăng budget chiến dịch thêm $10/ngày.',
    actionData: {
      currentBid: 1.15,
      newBid: 1.29,
      budgetIncreaseUsd: 10,
    },
    beforeState: { bid: 1.15, topOfSearchShare: '32%', weeklyOrders: 18 },
    proposedState: { bid: 1.29, topOfSearchShare: '68%', projectedWeeklyOrders: 35 },
    expectedImpact: 'Tăng thêm 65-75 đơn hàng/tháng với biên lợi nhuận ròng > 45%.',
    requiresExplicitApproval: true,
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-06T18:15:00Z',
  },
  {
    id: 'rec-05',
    clientId: 'client-lotus-03',
    clientName: 'Lotus Craft Vietnam',
    agentType: 'CUSTOMER',
    entityType: 'CUSTOMER_MESSAGE',
    entityId: 'msg-03',
    entityIdentifier: 'Order 114-2291039-4829102 (Bamboo Straws)',
    title: 'KHẨN CẤP: Phản hồi khách hàng có nguy cơ khiếu nại an toàn CPSC/FDA',
    description:
      'Khách hàng báo cáo trẻ nhỏ bị dằm cọ xát môi khi dùng ống hút tre. AI phát hiện từ khóa rủi ro pháp lý và tự động khóa tính năng trả lời tự động.',
    reason:
      'Theo quy chuẩn Vexim Compliance & Amazon Policy, mọi khiếu nại liên quan đến an toàn/chấn thương phải được Operations Manager trực tiếp kiểm tra và xử lý đền bù.',
    confidenceScore: 99,
    priority: 'CRITICAL',
    riskLevel: 'CRITICAL',
    proposedAction: 'Operations Manager gọi điện/soạn thư chính thức gửi khách, hoàn tiền 100% và kiểm tra lô sản xuất #LC26-04.',
    actionData: {
      customerName: 'Amanda R.',
      orderId: '114-2291039-4829102',
      lotNumber: 'LC26-04',
      suggestedRefund: 14.5,
    },
    expectedImpact: 'Ngăn chặn khiếu nại lên Amazon Trust & Safety và tránh bị khóa tài khoản người bán.',
    requiresExplicitApproval: true,
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-06T20:20:00Z',
  },
  {
    id: 'rec-06',
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    agentType: 'SALES',
    entityType: 'LISTING',
    entityId: 'prod-vina-02',
    entityIdentifier: 'SKU VXM-COCOA-PWD500',
    title: 'Phát hiện suy giảm tỷ lệ chuyển đổi (-8.4%) do đối thủ chạy Flash Deal $14.99',
    description:
      'Doanh thu SKU Bột Cacao giảm 12% tuần này. Phân tích nguyên nhân: Traffic vẫn duy trì ổn định (3,200 sessions), nhưng Conversion Rate giảm từ 10.2% xuống 8.4%. Đối thủ "Navitas Organics" đang chạy Coupon 20% đẩy giá về $14.99.',
    reason:
      'Khách hàng so sánh giá trước khi mua bột cacao 500g. Mức chênh lệch $2.00 đang làm giảm tỷ lệ add-to-cart.',
    confidenceScore: 91,
    priority: 'HIGH',
    riskLevel: 'MEDIUM',
    proposedAction: 'Kích hoạt Coupon 10% ($1.70 off) trong 7 ngày và bổ sung badge so sánh độ đậm đà 24% bơ cacao.',
    actionData: {
      couponValuePercent: 10,
      durationDays: 7,
      estimatedCost: 150,
    },
    beforeState: { currentPrice: 16.99, conversionRate: '8.4%', weeklyUnits: 110 },
    proposedState: { effectivePrice: 15.29, projectedConversionRate: '11.5%', projectedWeeklyUnits: 165 },
    expectedImpact: 'Phục hồi doanh số thêm +$930/tuần và bảo vệ thị phần Organic.',
    requiresExplicitApproval: true,
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-06T14:00:00Z',
  },
  {
    id: 'rec-07',
    clientId: 'client-highlands-04',
    clientName: 'Highlands Cashew Co.',
    agentType: 'COMPLIANCE',
    entityType: 'COMPLIANCE',
    entityId: 'comp-01',
    entityIdentifier: 'SKU VXM-CASH-ROAST500 (Hạt Điều Rang)',
    title: 'Chặn phát hành Amazon US — Yêu cầu in nhãn phụ cảnh báo Dị Ứng Hạt chuẩn FDA',
    description:
      'AI Compliance Engine quét bao bì sản phẩm và phát hiện thiếu dòng chữ "Contains: Cashews (Tree Nuts)" chuẩn đạo luật FALCPA của FDA Hoa Kỳ.',
    reason:
      'Đưa sản phẩm thực phẩm thiếu cảnh báo dị ứng lên Amazon US có nguy cơ bị Hải quan CBP giữ tại cảng hoặc Amazon FBA thu hồi hàng loạt.',
    confidenceScore: 99,
    priority: 'CRITICAL',
    riskLevel: 'CRITICAL',
    proposedAction: 'Khóa trạng thái Launch; tạo task gửi file thiết kế nhãn sticker phụ chuẩn FDA cho xưởng Bình Phước.',
    actionData: {
      sku: 'VXM-CASH-ROAST500',
      actionType: 'BLOCK_LAUNCH_UNTIL_FIXED',
    },
    expectedImpact: 'Bảo vệ an toàn pháp lý cho nhà cung cấp và tránh phạt tiền lên tới $10,000 từ FDA.',
    requiresExplicitApproval: true,
    status: 'PENDING_APPROVAL',
    createdAt: '2026-09-05T09:00:00Z',
  },
]

export const mockTasks: OperationalTask[] = [
  {
    id: 'task-1021',
    taskNumber: 1021,
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    title: 'Kiểm tra và xác nhận Purchase Order 1,200 units SKU VXM-COCOA-70DK',
    description:
      'Tồn kho FBA chỉ còn 11.8 ngày. Cần làm việc với xưởng Bến Tre để chốt lịch xuất xưởng trước ngày 14/09.',
    priority: 'CRITICAL',
    status: 'WAITING_APPROVAL',
    assignedTo: 'Trần Minh Tuấn (Ops Specialist)',
    assignedRole: 'OPS_MANAGER',
    dueDate: '2026-09-09',
    source: 'AI_INVENTORY_AGENT',
    linkedEntity: { type: 'INVENTORY', id: 'inv-01', name: 'VXM-COCOA-70DK' },
    recommendationId: 'rec-01',
    createdAt: '2026-09-07T06:05:00Z',
    updatedAt: '2026-09-07T06:05:00Z',
  },
  {
    id: 'task-1022',
    taskNumber: 1022,
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    title: 'Phê duyệt điều chỉnh giảm 35% bid từ khóa broad "cheap dark candy bar"',
    description: 'ACOS đang ở mức 88.03%. Cần review và thực thi trên Seller Central Campaign Manager.',
    priority: 'HIGH',
    status: 'OPEN',
    assignedTo: 'Lê Hoàng Yến (PPC Lead)',
    assignedRole: 'OPS_MANAGER',
    dueDate: '2026-09-08',
    source: 'AI_PPC_AGENT',
    linkedEntity: { type: 'CAMPAIGN', id: 'camp-02', name: 'SP_DarkChoc_Broad' },
    recommendationId: 'rec-02',
    createdAt: '2026-09-07T05:35:00Z',
    updatedAt: '2026-09-07T05:35:00Z',
  },
  {
    id: 'task-1023',
    taskNumber: 1023,
    clientId: 'client-lotus-03',
    clientName: 'Lotus Craft Vietnam',
    title: 'Xử lý khiếu nại an toàn dằm tre đơn hàng #114-2291039 & kiểm định lô LC26-04',
    description: 'Khách hàng phản ánh nguy cơ dị vật/dằm. Phải phản hồi trong vòng 2 giờ và hoàn tiền.',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    assignedTo: 'Alex Nguyen (Account Executive)',
    assignedRole: 'ACCOUNT_EXECUTIVE',
    dueDate: '2026-09-07',
    source: 'AI_HEALTH_AGENT',
    linkedEntity: { type: 'ORDER', id: 'ord-114-2291039-4829102', name: '114-2291039-4829102' },
    recommendationId: 'rec-05',
    createdAt: '2026-09-06T20:25:00Z',
    updatedAt: '2026-09-07T07:10:00Z',
  },
  {
    id: 'task-1024',
    taskNumber: 1024,
    clientId: 'client-highlands-04',
    clientName: 'Highlands Cashew Co.',
    title: 'Thiết kế nhãn phụ FDA Nutrition Facts & Cảnh báo Tree Nuts cho Hạt Điều',
    description: 'Gửi mẫu thiết kế nhãn sticker đạt chuẩn FDA 2026 cho đội sản xuất xưởng Bình Phước.',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    assignedTo: 'Vũ Hải Đăng (Compliance Lead)',
    assignedRole: 'COMPLIANCE_SPECIALIST',
    dueDate: '2026-09-12',
    source: 'AI_LISTING_AGENT',
    linkedEntity: { type: 'PRODUCT', id: 'prod-highlands-01', name: 'VXM-CASH-ROAST500' },
    recommendationId: 'rec-07',
    createdAt: '2026-09-05T09:10:00Z',
    updatedAt: '2026-09-06T15:00:00Z',
  },
  {
    id: 'task-1025',
    taskNumber: 1025,
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    title: 'Đồng bộ A+ Content Brand Story & Video giới thiệu vùng nguyên liệu Bến Tre',
    description: 'Đã hoàn tất chỉnh sửa Video phụ đề tiếng Anh 4K. Cần submit Amazon A+ Content Manager.',
    priority: 'MEDIUM',
    status: 'COMPLETED',
    assignedTo: 'Ngô Mỹ Linh (Content Specialist)',
    assignedRole: 'OPS_MANAGER',
    dueDate: '2026-09-05',
    source: 'MANUAL_OPS',
    linkedEntity: { type: 'LISTING', id: 'list-01', name: 'A+ Content Vina 70%' },
    createdAt: '2026-09-03T10:00:00Z',
    updatedAt: '2026-09-05T16:30:00Z',
  },
]

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: 'audit-01',
    timestamp: '2026-09-07 08:32:10 UTC',
    actorName: 'Alex Nguyen',
    actorRole: 'OPS_MANAGER',
    source: 'HUMAN',
    agentType: 'PPC',
    actionType: 'APPROVE_PPC_BID_CHANGE',
    entityType: 'PpcKeyword',
    entityId: 'kw-01',
    entityName: 'SP_Chocolate_Exact (vietnamese dark chocolate)',
    beforeValue: 'Bid: $1.15 | Target ACOS: 25%',
    afterValue: 'Bid: $1.25 | Target ACOS: 25%',
    approvalNotes: 'Phê duyệt theo đề xuất AI PPC Agent nhằm scale lượng đơn hàng cao điểm mùa Thu.',
    ipAddress: '113.161.72.10',
  },
  {
    id: 'audit-02',
    timestamp: '2026-09-07 06:10:04 UTC',
    actorName: 'AI Operations Orchestrator',
    actorRole: 'SUPER_ADMIN',
    source: 'AI_AGENT',
    agentType: 'INVENTORY',
    actionType: 'CREATE_STOCKOUT_WARNING',
    entityType: 'InventoryItem',
    entityId: 'inv-01',
    entityName: 'VXM-COCOA-70DK',
    beforeValue: 'Days of supply: 14.2d',
    afterValue: 'Days of supply: 11.8d (CRITICAL)',
    approvalNotes: 'Tự động tính toán rủi ro đứt hàng và tạo Task #1021 cho bộ phận Vận hành.',
    ipAddress: '10.0.4.12',
  },
  {
    id: 'audit-03',
    timestamp: '2026-09-06 21:05:40 UTC',
    actorName: 'Vexim SP-API Connector',
    actorRole: 'SUPER_ADMIN',
    source: 'SP_API_SYNC',
    actionType: 'SYNC_AMAZON_ORDERS',
    entityType: 'OrdersFeed',
    entityId: 'feed-901823',
    entityName: 'Amazon US Orders (Last 24h)',
    beforeValue: '2,810 orders synced',
    afterValue: '2,845 orders synced (+35 new orders)',
    approvalNotes: 'Đồng bộ SP-API định kỳ thành công. Không có lỗi phân tích dữ liệu.',
    ipAddress: '54.239.28.11',
  },
]

export const mockSyncJobs: SyncJob[] = [
  {
    id: 'job-01',
    name: 'Amazon Orders & Fulfillment Sync (FBA/FBM)',
    module: 'ORDERS',
    frequency: '1_HOUR',
    status: 'SYNC_SUCCESS',
    lastRunTime: '4 phút trước (08:40 UTC)',
    nextRunTime: 'Trong 56 phút (09:40 UTC)',
    itemsProcessed: 35,
    errorCount: 0,
  },
  {
    id: 'job-02',
    name: 'FBA Real-time Inventory & Inbound Tracking',
    module: 'INVENTORY',
    frequency: '1_HOUR',
    status: 'SYNC_SUCCESS',
    lastRunTime: '12 phút trước (08:32 UTC)',
    nextRunTime: 'Trong 48 phút (09:32 UTC)',
    itemsProcessed: 48,
    errorCount: 0,
  },
  {
    id: 'job-03',
    name: 'Amazon Advertising Reports (SP / SB / SD)',
    module: 'PERFORMANCE_ADS',
    frequency: '6_HOURS',
    status: 'SYNC_SUCCESS',
    lastRunTime: '2 giờ trước (06:30 UTC)',
    nextRunTime: 'Trong 4 giờ (12:30 UTC)',
    itemsProcessed: 14,
    errorCount: 0,
  },
  {
    id: 'job-04',
    name: 'AI Multi-Agent Nightly Operations & Health Scan',
    module: 'AI_NIGHTLY_SCAN',
    frequency: '24_HOURS',
    status: 'SYNC_SUCCESS',
    lastRunTime: 'Hôm nay lúc 04:00 UTC',
    nextRunTime: 'Ngày mai lúc 04:00 UTC',
    itemsProcessed: 112,
    errorCount: 0,
  },
]

export const mockClientReports: ClientPerformanceReport[] = [
  {
    id: 'rep-vina-aug2026',
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    period: 'LAST_30_DAYS',
    startDate: '2026-08-08',
    endDate: '2026-09-07',
    grossSales: 68420.0,
    previousGrossSales: 57800.0,
    salesGrowthPercent: 18.37,
    unitsSold: 2845,
    ordersCount: 2190,
    averageOrderValue: 31.24,
    conversionRate: 12.4,
    previousConversionRate: 10.8,
    sessions: 22940,
    adSpend: 9850.0,
    adSales: 41200.0,
    acos: 23.9,
    tacos: 14.39,
    estimatedGrossProfit: 27950.0,
    estimatedNetMarginPercent: 40.85,
    executiveSummaryVi:
      'Tháng vừa qua, doanh thu Vinacacao trên Amazon US đạt 68,420 USD (tăng +18.37% so với tháng trước). Tỷ lệ chuyển đổi cải thiện mạnh từ 10.8% lên 12.4% nhờ việc Vexim tối ưu lại hình ảnh và cấu trúc A+ Content. Chiến dịch PPC duy trì hiệu quả cao với ACOS đạt 23.9% (dưới ngưỡng mục tiêu 25%). Tuy nhiên, SKU chủ lực VXM-COCOA-70DK đang có nguy cơ hết hàng FBA trong 11 ngày tới. Vexim khuyến nghị quý công ty duyệt ngay đơn sản xuất 1,200 units và kết hợp chuyển 300 units đường hàng không để duy trì thứ hạng Best Seller.',
    topPerformers: [
      { sku: 'VXM-COCOA-70DK', title: '70% Dark Chocolate Pack of 4', revenue: 42100, units: 1684 },
      { sku: 'VXM-COCOA-PWD500', title: 'Pure Cocoa Powder 500g', revenue: 19800, units: 1165 },
    ],
    keyRisksAndActionPlan: [
      'Rủi ro hết hàng SKU Chocolate 70% trong 11.8 ngày -> Cần phê duyệt PO sản xuất khẩn cấp.',
      'Cạnh tranh gia tăng tại ngách Bột Cacao -> Vexim đề xuất chạy coupon kích cầu 10% trong 7 ngày tới.',
      'Chuẩn bị cho mùa mua sắm Q4 Black Friday & Cyber Monday -> Dự kiến cần tăng lượng tồn kho an toàn lên 200%.',
    ],
    generatedAt: '2026-09-07T08:00:00Z',
  },
]

export const mockAgencyKpis: VeximAgencyKPIs = {
  totalManagedClients: 5,
  activeManagedSkus: 46,
  totalManagedRevenueMonthly: 154270,
  averageClientGrowthRate: 19.34,
  totalOpenIssues: 7,
  totalAIRecommendationsGenerated: 142,
  humanApprovedRecommendations: 108,
  executedRecommendations: 104,
  aiAssistedOperationsRate: 74.8, // 74.8% AI-assisted operations rate!
  humanHoursSavedThisMonth: 342,
  serviceRevenueBreakdown: {
    amazonAudit: 1200,
    amazonLaunch: 4500,
    amazonOperations: 7500,
    amazonGrowth: 12500,
  },
}

// ==========================================
// VEXIM PLATFORM V2.0 - DEEP TECH MOCK DATA
// ==========================================

import {
  AlgorithmicBidRule,
  HarvestedSearchTerm,
  CannibalizationAlert,
  DynamicLeadTimeRoute,
  GeoFbaPlacementOption,
  CompetitorReverseAsin,
  CroMetricInput,
  PoaDocument,
  TrademarkWatch,
} from './types'

export const mockAlgorithmicBidRules: AlgorithmicBidRule[] = [
  {
    id: 'rule-dayparting-01',
    ruleName: 'Q4 US Day-parting Peak Hours Multiplier',
    ruleType: 'DAY_PARTING',
    targetCampaignIds: ['cmp-sp-01', 'cmp-sp-02'],
    parameters: {
      peakHoursBidMultiplier: 1.25, // +25% from 18:00 - 23:00 EST
      offPeakBidMultiplier: 0.60,   // -40% from 01:00 - 06:00 EST
      topOfSearchMultiplier: 1.35,
    },
    status: 'ACTIVE',
    executionsCount24h: 48,
    estimatedDailySavingsUsd: 46.80,
    lastTriggeredAt: '2026-09-08T06:00:00Z',
  },
  {
    id: 'rule-inventory-throttle-02',
    ruleName: 'Low FBA Stock Auto-Bid Dampener (OOS Shield)',
    ruleType: 'INVENTORY_THROTTLE',
    targetCampaignIds: ['cmp-sp-01'],
    parameters: {
      stockoutThresholdDays: 14,
      offPeakBidMultiplier: 0.70, // Giảm 30% bid khi tồn < 14 ngày để tránh đứt hàng đột ngột
    },
    status: 'ACTIVE',
    executionsCount24h: 12,
    estimatedDailySavingsUsd: 32.50,
    lastTriggeredAt: '2026-09-08T07:15:00Z',
  },
  {
    id: 'rule-target-acos-03',
    ruleName: 'Dynamic Target ACOS Auto-Bid Balancer',
    ruleType: 'TARGET_ACOS_TUNER',
    targetCampaignIds: ['cmp-sp-02', 'cmp-sb-01'],
    parameters: {
      targetAcosThreshold: 22.0,
    },
    status: 'ACTIVE',
    executionsCount24h: 84,
    estimatedDailySavingsUsd: 68.20,
    lastTriggeredAt: '2026-09-08T07:45:00Z',
  },
]

export const mockHarvestedSearchTerms: HarvestedSearchTerm[] = [
  {
    id: 'harvest-01',
    campaignName: 'SP - Dark Chocolate - Auto Discovery',
    adGroupName: 'Close Match - 70% Bars',
    searchTerm: 'vietnamese single origin dark chocolate 70%',
    matchTypeSource: 'AUTO',
    impressions: 4820,
    clicks: 142,
    orders: 34,
    spend: 128.40,
    sales: 849.66,
    acos: 15.11,
    cvr: 23.94,
    suggestedAction: 'PROMOTE_EXACT',
    confidenceScore: 98,
    status: 'PENDING',
  },
  {
    id: 'harvest-02',
    campaignName: 'SP - Cocoa Powder - Broad Scale',
    adGroupName: 'Baking Powder Broad',
    searchTerm: 'cheap baking powder bulk 10kg restaurant',
    matchTypeSource: 'BROAD',
    impressions: 2940,
    clicks: 68,
    orders: 0,
    spend: 74.80,
    sales: 0,
    acos: 0,
    cvr: 0,
    suggestedAction: 'ADD_NEGATIVE_EXACT',
    confidenceScore: 95,
    status: 'PENDING',
  },
  {
    id: 'harvest-03',
    campaignName: 'SP - Dark Chocolate - Broad',
    adGroupName: 'Artisan Chocolate Broad',
    searchTerm: 'keto dairy free dark chocolate bar',
    matchTypeSource: 'BROAD',
    impressions: 6200,
    clicks: 188,
    orders: 29,
    spend: 169.20,
    sales: 724.71,
    acos: 23.35,
    cvr: 15.42,
    suggestedAction: 'PROMOTE_EXACT',
    confidenceScore: 92,
    status: 'PENDING',
  },
  {
    id: 'harvest-04',
    campaignName: 'SP - Cocoa Powder - Auto',
    adGroupName: 'Loose Match',
    searchTerm: 'hot chocolate mix with marshmallows sweet',
    matchTypeSource: 'AUTO',
    impressions: 1840,
    clicks: 45,
    orders: 1,
    spend: 58.50,
    sales: 16.99,
    acos: 344.32,
    cvr: 2.22,
    suggestedAction: 'ADD_NEGATIVE_EXACT',
    confidenceScore: 89,
    status: 'PENDING',
  },
]

export const mockCannibalizationAlerts: CannibalizationAlert[] = [
  {
    id: 'cannibal-01',
    keyword: 'organic dark chocolate bar 70',
    campaignCount: 2,
    conflictingSkus: [
      { sku: 'VXM-COCOA-70DK', title: '70% Dark Chocolate Pack 4', currentBid: 1.45, acos: 18.2 },
      { sku: 'VXM-COCOA-85DK', title: '85% Extra Dark Bar Pack 4', currentBid: 1.60, acos: 29.4 },
    ],
    combinedMonthlySpend: 420.50,
    wastedSpendEstimate: 118.00,
    recommendation: 'Phân tách từ khóa "organic dark chocolate bar 70" chỉ nhắm vào SKU 70DK, SKU 85DK chuyển sang từ khóa ngách "85% intense bitter chocolate" để tránh đẩy giá thầu nội bộ.',
  },
]

export const mockDynamicLeadTimeRoutes: DynamicLeadTimeRoute[] = [
  {
    id: 'route-catlai-lax',
    originPort: 'Cảng Cát Lái (Hồ Chí Minh)',
    destinationPort: 'Port of Long Beach / Los Angeles, CA',
    destinationFbaHub: 'West Coast Regional Hub (ONT8 / LAX9)',
    factoryProductionDays: 14,
    oceanTransitDays: 22,
    portCustomsClearanceDays: 4,
    domesticDrayageDays: 2,
    fbaCheckinDays: 5,
    totalLeadTimeDays: 47,
    historicalAverageDays: 38,
    congestionDelayDays: 9,
    riskFactors: [
      { factor: 'Mùa cao điểm xuất hàng Q4 (Peak Season Surcharge)', severity: 'HIGH', notes: 'Tàu container tuyến Trans-Pacific kín chỗ, đề xuất book tàu trước 3 tuần' },
      { factor: 'Kiểm tra FDA ngẫu nhiên tại Cảng Los Angeles', severity: 'MEDIUM', notes: 'Cần nộp FDA Prior Notice điện tử trước khi tàu cập bến 5 ngày' },
    ],
    seasonalSurgeForecast: 'Dự báo tháng 10-11/2026 thời gian thông quan tại LA kéo dài thêm +5 đến +7 ngày do tắc nghẽn kho cảng.',
  },
  {
    id: 'route-haiphong-ny',
    originPort: 'Cảng Hải Phòng (Lạch Huyện)',
    destinationPort: 'Port of New York / New Jersey',
    destinationFbaHub: 'East Coast Regional Hub (TEB9 / ABE8)',
    factoryProductionDays: 12,
    oceanTransitDays: 32,
    portCustomsClearanceDays: 3,
    domesticDrayageDays: 3,
    fbaCheckinDays: 6,
    totalLeadTimeDays: 56,
    historicalAverageDays: 48,
    congestionDelayDays: 8,
    riskFactors: [
      { factor: 'Thời gian đi đường biển qua kênh đào Suez/Panama', severity: 'HIGH', notes: 'Hạn hán kênh đào Panama có thể làm trễ 4-6 ngày' },
    ],
    seasonalSurgeForecast: 'Tuyến Bờ Đông ổn định hơn về thông quan nhưng lead-time dài hơn bờ Tây 9 ngày.',
  },
]

export const mockGeoFbaPlacements: GeoFbaPlacementOption[] = [
  {
    id: 'placement-split-opt',
    strategyName: 'Amazon Inbound Multi-Location Split (Tối ưu Phí FBA 2026)',
    description: 'Chia lô hàng 3,000 units thành 2 điểm nhận: 60% Bờ Tây (ONT8 - CA) + 40% Bờ Đông (TEB9 - NJ). Miễn giảm hoàn toàn Inbound Placement Service Fee.',
    fbaPlacementFeePerUnit: 0.00,
    totalPlacementFeeUsd: 0.00,
    inboundFreightCostUsd: 1420.00,
    totalInboundCostUsd: 1420.00,
    regionalBreakdown: [
      { region: 'Bờ Tây (California & Pacific)', warehouseCode: 'ONT8 (Moreno Valley, CA)', percentage: 60, units: 1800 },
      { region: 'Bờ Đông (New York & Tristate)', warehouseCode: 'TEB9 (Somerset, NJ)', percentage: 40, units: 1200 },
    ],
    avgDeliveryTimeToPrimeBuyer: '1.2 ngày (92% khách Prime nhận Same-Day / 1-Day)',
    savingsVsSingleDestinationUsd: 840.00,
    recommended: true,
  },
  {
    id: 'placement-single-west',
    strategyName: 'Minimal Inbound Splits (Gửi 1 điểm duy nhất Bờ Tây)',
    description: 'Gửi toàn bộ 3,000 units vào 1 kho ONT8 (California). Amazon tự luân chuyển nội bộ và thu phí Inbound Placement Fee $0.28/unit.',
    fbaPlacementFeePerUnit: 0.28,
    totalPlacementFeeUsd: 840.00,
    inboundFreightCostUsd: 980.00,
    totalInboundCostUsd: 1820.00,
    regionalBreakdown: [
      { region: 'Bờ Tây (Toàn bộ lô hàng)', warehouseCode: 'ONT8 (Moreno Valley, CA)', percentage: 100, units: 3000 },
    ],
    avgDeliveryTimeToPrimeBuyer: '2.4 ngày (Amazon mất 5-7 ngày FC Transfer)',
    savingsVsSingleDestinationUsd: 0.00,
    recommended: false,
  },
]

export const mockCompetitorReverseAsins: CompetitorReverseAsin[] = [
  {
    id: 'comp-lindt-01',
    competitorAsin: 'B079NB7N64',
    competitorBrand: 'Lindt Excellence',
    productTitle: 'Lindt Excellence 70% Cocoa Dark Chocolate Bar, 3.5 oz (Pack of 12)',
    estimatedMonthlyUnits: 14200,
    estimatedMonthlyRevenueUsd: 355000,
    price: 24.99,
    bsrRank: 42,
    reviewCount: 18940,
    reviewRating: 4.7,
    sharedTopKeywords: [
      { keyword: 'dark chocolate bar 70', competitorOrganicRank: 2, ourOrganicRank: 8, searchVolume: 42100 },
      { keyword: 'single origin dark chocolate', competitorOrganicRank: 12, ourOrganicRank: 3, searchVolume: 12400 },
      { keyword: 'keto organic chocolate bar', competitorOrganicRank: 8, ourOrganicRank: 6, searchVolume: 18500 },
    ],
    keywordOverlapScore: 84,
    pricingStrategyInsight: 'Lindt duy trì pack 12 giá $24.99 ($2.08/bar). Vinacacao có lợi thế hương vị Single Origin Đắk Lắk, đề xuất làm nổi bật "Single Origin Vietnam Cocoa Butter" trên Hero Image 2 để cướp traffic organic.',
  },
  {
    id: 'comp-altereco-02',
    competitorAsin: 'B08F9Q82LZ',
    competitorBrand: 'Alter Eco Organic',
    productTitle: 'Alter Eco Organic 85% Dark Chocolate Bar, Fair Trade Certified',
    estimatedMonthlyUnits: 6800,
    estimatedMonthlyRevenueUsd: 169932,
    price: 24.99,
    bsrRank: 118,
    reviewCount: 4320,
    reviewRating: 4.6,
    sharedTopKeywords: [
      { keyword: 'fair trade dark chocolate', competitorOrganicRank: 1, ourOrganicRank: 14, searchVolume: 9800 },
      { keyword: 'vegan dark chocolate bars', competitorOrganicRank: 4, ourOrganicRank: 9, searchVolume: 24000 },
    ],
    keywordOverlapScore: 71,
    pricingStrategyInsight: 'Đối thủ đánh mạnh vào chứng chỉ Fair Trade & Non-GMO. Vinacacao cần đẩy mạnh chứng chỉ USDA Organic & Vietnam Direct-Trade Farm để kéo điểm chuyển đổi.',
  },
]

// Sprint audit: CHỈ giữ các chỉ số phiên (SP-API Business Report — hiện SIMULATED).
// Mọi số suy ra (sessions, uplift, loại nghẽn, chẩn đoán) do lib/cro-engine.ts tính —
// KHÔNG còn lưu sẵn +$4,620/+$2,840 hay câu chẩn đoán nào trong data.
export const mockCroMetricInputs: CroMetricInput[] = [
  {
    sku: 'VXM-COCOA-70DK',
    asin: 'B0DC89X102',
    title: 'Vinacacao 70% Dark Chocolate Bar 4-Pack (Single Origin Vietnam)',
    ctr: 0.48,
    categoryBenchmarkCtr: 0.65,
    unitSessionPercentage: 14.8,
    categoryBenchmarkCvr: 11.2,
    bounceRate: 34.2,
  },
  {
    sku: 'VXM-COCOA-PWD500',
    asin: 'B0DC90Y203',
    title: 'Pure Organic Vietnamese Cocoa Powder 500g (Unsweetened)',
    ctr: 0.82,
    categoryBenchmarkCtr: 0.65,
    unitSessionPercentage: 7.4,
    categoryBenchmarkCvr: 10.5,
    bounceRate: 58.6,
  },
]

export const mockPoaDocuments: PoaDocument[] = [
  {
    id: 'poa-foodsafety-01',
    issueId: 'case-amazon-health-01',
    asin: 'B0DC90Y203',
    productName: 'Pure Organic Vietnamese Cocoa Powder 500g',
    amazonNoticeType: 'FOOD_SAFETY_EXPIRATION',
    dateReceived: '2026-09-06T10:00:00Z',
    deadlineDate: '2026-09-13T23:59:59Z',
    rootCauseAnalysisVi: 'Nguyên nhân gốc rễ: Một khách hàng nhận gói bột cacao và phàn nàn hạn sử dụng bị mờ nhạt do mực in phun nhiệt trên dây chuyền đóng gói số 2 tại nhà máy Bến Tre bị lệch cảm biến laser.',
    rootCauseAnalysisEn: 'Root Cause: A customer received a cocoa powder pouch where the expiration date (EXP: 12/2027) was faintly printed due to a thermal inkjet sensor misalignment on Packaging Line #2 at our Ben Tre manufacturing facility.',
    immediateCorrectiveActionsVi: 'Hành động khắc phục ngay lập tức: (1) Đã hoàn tiền 100% kèm thư xin lỗi và gửi tặng 1 gói mới có date in rõ ràng. (2) Tạo lệnh FBA Removal Order kiểm tra toàn bộ 48 gói cùng Batch #VN2026-08 tại kho FBA ONT8.',
    immediateCorrectiveActionsEn: 'Immediate Corrective Actions: (1) 100% refund issued with formal apology and complimentary replacement sent. (2) FBA Removal Order #REM-9821 submitted to inspect and quarantine all remaining 48 units of Batch #VN2026-08 at ONT8 fulfillment center.',
    preventiveMeasuresVi: 'Biện pháp phòng ngừa dài hạn: (1) Nâng cấp hệ thống máy in date sang công nghệ khắc Laser vĩnh viễn (Laser Date Coding). (2) Bổ sung trạm kiểm tra chất lượng tự động (Vision Inspection System) 100% sản phẩm trước khi xuất xưởng.',
    preventiveMeasuresEn: 'Long-term Preventive Measures: (1) Upgraded facility packaging lines to permanent Fiber Laser Date Coders. (2) Installed high-speed automated Optical Inspection Camera to verify 100% legibility of Lot & Expiry on outer cartons before ocean shipment.',
    attachedEvidence: [
      { name: 'Certificate of Analysis (COA) Batch #VN2026-08', type: 'PDF', url: '/docs/coa-vn2026.pdf', verified: true },
      { name: 'Commercial Invoice & Factory Audit Report', type: 'PDF', url: '/docs/factory-audit.pdf', verified: true },
      { name: 'Laser Coding Upgrade Work Order & Photos', type: 'IMAGE', url: '/docs/laser-upgrade.jpg', verified: true },
    ],
    status: 'READY_FOR_LEGAL_REVIEW',
    attorneyApproved: true,
  },
]

export const mockTrademarkWatches: TrademarkWatch[] = [
  {
    id: 'uspto-watch-01',
    trademarkName: 'VINACACAO TROPICALS',
    serialNumber: '98472910',
    applicantName: 'Global Brands Import LLC (Delaware, USA)',
    filingDate: '2026-08-14',
    usptoClass: 'Class 30: Cocoa, chocolate confectionery, bakery mixes',
    similarityScore: 89,
    status: 'PUBLISHED_FOR_OPPOSITION',
    oppositionDeadline: '2026-10-15',
    riskAssessmentVi: 'RỦI RO CAO: Đơn vị trung gian tại Delaware đang nộp đơn đăng ký nhãn hiệu có tiền tố VINACACAO trong cùng nhóm ngành Class 30. Nếu không nộp đơn phản đối (Notice of Opposition) trước ngày 15/10/2026, họ có thể kiện ngược lại store Vinacacao trên Amazon US.',
    recommendedLegalAction: 'Yêu cầu luật sư sở hữu trí tuệ tại Mỹ nộp ngay "Notice of Opposition" dựa trên quyền sở hữu thương hiệu Vinacacao đã đăng ký tại Việt Nam và quyền sử dụng trước (Prior Use in Commerce) tại Mỹ.',
  },
  {
    id: 'uspto-watch-02',
    trademarkName: 'AN AN PURE INCENSE',
    serialNumber: '98501244',
    applicantName: 'Zen Living Goods Inc (California, USA)',
    filingDate: '2026-08-28',
    usptoClass: 'Class 03: Incense, essential oils, aromatherapy',
    similarityScore: 78,
    status: 'PENDING_EXAMINATION',
    oppositionDeadline: '2026-11-30',
    riskAssessmentVi: 'RỦI RO TRUNG BÌNH: Đang trong giai đoạn thẩm tra tại USPTO. Thẩm định viên có khả năng sẽ từ chối do trùng lặp nhãn hiệu Thảo Mộc An An đã nộp trước.',
    recommendedLegalAction: 'Theo dõi tiến trình thẩm tra (USPTO Office Action) và chuẩn bị thư cảnh báo (Cease & Desist) nếu nhãn hiệu vượt qua vòng thẩm tra.',
  },
]

// Master Admin Team Members Mock Data
import { TeamMember } from './types'

export const mockTeamMembers: TeamMember[] = [
  {
    id: 'user-01-superadmin',
    fullName: 'Lương Văn Học',
    email: 'hocluongvan88@gmail.com',
    password: '••••••••', // demo — quản lý ở lib/auth-constants.ts
    role: 'SUPER_ADMIN',
    department: 'Ban Điều Hành & Quản Trị Tối Cao',
    title: 'Chief Executive Officer & Super Admin',
    assignedClientIds: ['ALL'],
    canApproveHighRisk: true,
    status: 'ACTIVE',
    lastActive: 'Đang hoạt động (Phiên chính)',
    phone: '+84 988 888 888',
    twoFactorEnabled: true,
    createdAt: '2025-01-01',
  },
  {
    id: 'user-02-ops',
    fullName: 'Nguyễn Tuấn Anh',
    email: 'hocluongvan25@gmail.com',
    password: '••••••••', // demo — quản lý ở lib/auth-constants.ts
    role: 'OPS_MANAGER',
    department: 'Ban Quản Trị & Vận Hành Tổng Thể',
    title: 'Amazon Operations Director',
    assignedClientIds: ['ALL'],
    canApproveHighRisk: true,
    status: 'ACTIVE',
    lastActive: '10 phút trước',
    phone: '+84 925 252 525',
    twoFactorEnabled: true,
    createdAt: '2025-02-15',
  },
  {
    id: 'user-03-ppc',
    fullName: 'Lương Hoàng Minh',
    email: 'luonghoangminh88@gmail.com',
    password: '••••••••', // demo — quản lý ở lib/auth-constants.ts
    role: 'PPC_SPECIALIST',
    department: 'Team Quảng Cáo & Growth PPC',
    title: 'Lead PPC & Growth Engineering Specialist',
    assignedClientIds: ['client-vina-01', 'client-anan-02'],
    canApproveHighRisk: false,
    status: 'ACTIVE',
    lastActive: '5 phút trước',
    phone: '+84 988 123 456',
    twoFactorEnabled: false,
    createdAt: '2025-03-01',
  },
  {
    id: 'user-04-logistics',
    fullName: 'Ánh Nguyễn',
    email: 'anhnguyen94@gmail.com',
    password: '••••••••', // demo — quản lý ở lib/auth-constants.ts
    role: 'SUPPLY_CHAIN_SPECIALIST',
    department: 'Team Kho Vận & Chuỗi Cung Ứng FBA',
    title: 'Senior FBA Logistics & 3PL Manager',
    assignedClientIds: ['client-vina-01', 'client-anan-02'],
    canApproveHighRisk: false,
    status: 'ACTIVE',
    lastActive: '25 phút trước',
    phone: '+84 994 949 494',
    twoFactorEnabled: false,
    createdAt: '2025-03-10',
  },
  {
    id: 'user-05-brand',
    fullName: 'Trần Thu Hà',
    email: 'hocluongvan26@gmail.com',
    password: '••••••••', // demo — quản lý ở lib/auth-constants.ts
    role: 'BRAND_CS_SPECIALIST',
    department: 'Team Listing, CRO & Chăm Sóc Khách Hàng',
    title: 'Brand Experience & Listing Optimization Manager',
    assignedClientIds: ['client-vina-01', 'client-anan-02'],
    canApproveHighRisk: false,
    status: 'ACTIVE',
    lastActive: '1 giờ trước',
    phone: '+84 926 262 626',
    twoFactorEnabled: false,
    createdAt: '2025-03-15',
  },
  {
    id: 'user-06-legal',
    fullName: 'Lê Hoàng Nam',
    email: 'hocluongvan2588@gmail.com',
    password: '••••••••', // demo — quản lý ở lib/auth-constants.ts
    role: 'COMPLIANCE_SPECIALIST',
    department: 'Team Pháp Lý, FDA & Soạn Đơn Kháng Cáo POA',
    title: 'Head of Amazon Compliance & Policy Counsel',
    assignedClientIds: ['ALL'],
    canApproveHighRisk: true,
    status: 'ACTIVE',
    lastActive: 'Hôm nay',
    phone: '+84 925 888 888',
    twoFactorEnabled: true,
    createdAt: '2025-02-01',
  },
  {
    id: 'user-07-ae',
    fullName: 'Phạm Minh Trang',
    email: 'hocluongvan2788@gmail.com',
    password: '••••••••', // demo — quản lý ở lib/auth-constants.ts
    role: 'ACCOUNT_EXECUTIVE',
    department: 'Team Quản Lý Khách Hàng & Đối Tác',
    title: 'Senior Account Executive',
    assignedClientIds: ['ALL'],
    canApproveHighRisk: false,
    status: 'ACTIVE',
    lastActive: 'Hôm qua',
    phone: '+84 927 888 888',
    twoFactorEnabled: false,
    createdAt: '2025-04-01',
  },
  {
    id: 'user-08-client-vina',
    fullName: 'Nguyễn Văn Hùng',
    email: 'hocluongvan22@gmail.com',
    password: '••••••••', // demo — quản lý ở lib/auth-constants.ts
    role: 'CLIENT_SUPPLIER',
    department: 'Công ty Cổ phần Vinacacao Việt Nam',
    title: 'Tổng Giám Đốc (CEO Vinacacao)',
    assignedClientIds: ['client-vina-01'],
    canApproveHighRisk: false,
    status: 'ACTIVE',
    lastActive: '3 giờ trước',
    phone: '+84 908 123 456',
    twoFactorEnabled: false,
    createdAt: '2025-05-10',
  },
  {
    id: 'user-09-client-anan',
    fullName: 'Trần Thị Thu Thảo',
    email: 'hocluongvvan33@gmail.com',
    password: '••••••••', // demo — quản lý ở lib/auth-constants.ts
    role: 'CLIENT_SUPPLIER',
    department: 'Công ty TNHH Thảo Mộc An An',
    title: 'Nhà Sáng Lập (Founder Thảo Mộc An An)',
    assignedClientIds: ['client-anan-02'],
    canApproveHighRisk: false,
    status: 'ACTIVE',
    lastActive: 'Hôm qua',
    phone: '+84 912 345 678',
    twoFactorEnabled: false,
    createdAt: '2025-06-01',
  },
]

export const mockNotifications: AppNotification[] = [
  {
    id: 'notif-01',
    title: '🚨 KHẨN CẤP (CPSC/FDA): Khiếu nại an toàn trẻ nhỏ',
    description: 'Khách hàng báo dằm cọ xát môi từ Thìa Gỗ Dừa. AI đã khóa auto-reply, chuyển phòng Pháp lý & Ops Lead.',
    type: 'CRITICAL_SAFETY',
    priority: 'CRITICAL',
    timestamp: '10 phút trước',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    isRead: false,
    targetRoles: ['COMPLIANCE_SPECIALIST', 'OPS_MANAGER', 'SUPER_ADMIN', 'BRAND_CS_SPECIALIST'],
    targetTab: 'customers',
    clientId: 'client-lotus-03',
    clientName: 'Lotus Craft Vietnam',
    actionBy: { name: 'AI Safety Monitor Guard', role: 'OPS_MANAGER' },
  },
  {
    id: 'notif-02',
    title: '🔴 CẢNH BÁO: SKU Socola 70% còn 11.8 ngày tồn kho FBA',
    description: 'Tồn kho khả dụng chỉ còn 168 units. Cần chuyển gấp 1,200 units từ kho 3PL California sang FBA.',
    type: 'LOW_STOCK',
    priority: 'HIGH',
    timestamp: '25 phút trước',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    isRead: false,
    targetRoles: ['SUPPLY_CHAIN_SPECIALIST', 'OPS_MANAGER', 'SUPER_ADMIN', 'CLIENT_SUPPLIER'],
    targetTab: 'supply-chain-hub',
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    actionBy: { name: 'AI Inventory Agent', role: 'SUPPLY_CHAIN_SPECIALIST' },
  },
  {
    id: 'notif-03',
    title: '⚠️ PHÁP LÝ FDA: Chặn Launch SKU do thiếu nhãn dị ứng',
    description: 'Hồ sơ Hạt điều thiếu câu "Contains: Cashews (Tree Nuts)" theo luật FALCPA của FDA Hoa Kỳ.',
    type: 'COMPLIANCE',
    priority: 'CRITICAL',
    timestamp: '1 giờ trước',
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    isRead: false,
    targetRoles: ['COMPLIANCE_SPECIALIST', 'OPS_MANAGER', 'SUPER_ADMIN'],
    targetTab: 'compliance-ops-desk',
    clientId: 'client-highlands-04',
    clientName: 'Highlands Cashew Co.',
    actionBy: { name: 'FDA Label Compliance Bot', role: 'COMPLIANCE_SPECIALIST' },
  },
  {
    id: 'notif-04',
    title: '🌟 PPC VÀNG: Thu hoạch từ khóa ACOS 12.4% (4 Orders)',
    description: 'Cụm từ "pure vietnamese dark cacao" đạt đủ điều kiện tự động cô lập sang chiến dịch Exact Match.',
    type: 'PPC_HARVEST',
    priority: 'HIGH',
    timestamp: '2 giờ trước',
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    isRead: true,
    targetRoles: ['PPC_SPECIALIST', 'ACCOUNT_EXECUTIVE', 'SUPER_ADMIN'],
    targetTab: 'ppc-growth-desk',
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    actionBy: { name: 'Lê Hoàng Yến (PPC Lead)', role: 'PPC_SPECIALIST' },
  },
  {
    id: 'notif-05',
    title: '🚢 TÀU BIỂN: Container VNM-LAX-88 đã thông quan Hải Quan',
    description: 'Hải quan CBP & FDA cấp phép Release. Xe kéo Drayage đang chuyển 5,000 units về kho 3PL.',
    type: 'LOGISTICS',
    priority: 'MEDIUM',
    timestamp: '4 giờ trước',
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    isRead: true,
    targetRoles: ['SUPPLY_CHAIN_SPECIALIST', 'OPS_MANAGER', 'SUPER_ADMIN', 'CLIENT_SUPPLIER'],
    targetTab: 'supply-chain-hub',
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    actionBy: { name: 'Trần Minh Tuấn (Logistics Lead)', role: 'SUPPLY_CHAIN_SPECIALIST' },
  },
  {
    id: 'notif-06',
    title: '🛡️ POA KHÁNG CÁO: Amazon chấp thuận mở khóa ASIN',
    description: 'Hồ sơ giải trình chuỗi cung ứng & COA phòng Lab ILAC đã được Amazon Seller Performance phê duyệt.',
    type: 'APPROVAL',
    priority: 'HIGH',
    timestamp: '5 giờ trước',
    createdAt: new Date(Date.now() - 300 * 60 * 1000).toISOString(),
    isRead: true,
    targetRoles: ['COMPLIANCE_SPECIALIST', 'OPS_MANAGER', 'SUPER_ADMIN', 'CLIENT_SUPPLIER'],
    targetTab: 'compliance-ops-desk',
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    actionBy: { name: 'Vũ Hải Đăng (Compliance Lead)', role: 'COMPLIANCE_SPECIALIST' },
  },
  {
    id: 'notif-07',
    title: '📊 BÁO CÁO P&L: Doanh thu tuần Vinacacao vượt mốc $18,450',
    description: 'Tăng trưởng +14.2% DoD, TACoS tối ưu ở mức 8.6%, tỷ suất hoàn vốn ROAS đạt 4.8x.',
    type: 'FINANCE',
    priority: 'MEDIUM',
    timestamp: '1 ngày trước',
    createdAt: new Date(Date.now() - 86400 * 1000).toISOString(),
    isRead: true,
    targetRoles: ['ACCOUNT_EXECUTIVE', 'SUPER_ADMIN', 'CLIENT_SUPPLIER'],
    targetTab: 'reports',
    clientId: 'client-vina-01',
    clientName: 'Vinacacao Organics',
    actionBy: { name: 'AI Financial Analyst', role: 'ACCOUNT_EXECUTIVE' },
  },
  {
    id: 'notif-08',
    title: '✨ LISTING CRO: Bản nháp tối ưu Listing chuẩn A9 đã xuất bản',
    description: 'Cập nhật Backend Search Terms & Visual A+ Content cho dòng Thìa Gỗ Dừa Xuất Khẩu.',
    type: 'LISTING',
    priority: 'MEDIUM',
    timestamp: '1 ngày trước',
    createdAt: new Date(Date.now() - 90000 * 1000).toISOString(),
    isRead: true,
    targetRoles: ['BRAND_CS_SPECIALIST', 'OPS_MANAGER', 'SUPER_ADMIN', 'CLIENT_SUPPLIER'],
    targetTab: 'brand-intelligence',
    clientId: 'client-lotus-03',
    clientName: 'Lotus Craft Vietnam',
    actionBy: { name: 'Ngô Mỹ Linh (Brand Specialist)', role: 'BRAND_CS_SPECIALIST' },
  },
]

// ====================================================================
// MOCK DATA: 5 CRITICAL OPERATIONAL LOGISTICS EXTENSIONS
// ====================================================================

export const mockReverseLogisticsItems: ReverseLogisticsItem[] = [
  {
    id: 'rev-01',
    clientId: 'client-vina-01',
    sku: 'VN-COCOA-ORGANIC-500G',
    asin: 'B0C7XYZ890',
    title: 'Bột Cacao Nguyên Chất Đắk Lắk Hữu Cơ 500g',
    imageUrl: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=300',
    unitsReturned: 42,
    returnReason: 'PACKAGING_TORN',
    fbaWarehouseOrigin: 'ONT8 (California)',
    removalOrderId: 'REM-2026-0902-ONT8',
    status: 'INSPECTED_AT_3PL',
    grade: 'GRADE_A_NEW',
    inspectionNotes: 'Hàng nguyên seal chất lượng bên trong 100%, chỉ bị móp méo hộp carton ngoài do Amazon vận chuyển nội địa. Đã thay vỏ hộp mới và dán lại tem FNSKU.',
    estimatedValueRecoveryUsd: 1150,
    relabelCostUsd: 14.7,
    recycledIntoFbaShipmentId: 'FBA18-INJ-VNCOCO-4412',
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'rev-02',
    clientId: 'client-anan-02',
    sku: 'VN-CASHEW-SALTED-W320',
    asin: 'B0C8ABC123',
    title: 'Hạt Điều Rang Muối Bình Phước Loại W320 Cao Cấp',
    imageUrl: 'https://images.unsplash.com/photo-1536591375315-1b836820db76?auto=format&fit=crop&q=80&w=300',
    unitsReturned: 28,
    returnReason: 'CUSTOMER_DEFECTIVE',
    fbaWarehouseOrigin: 'LGB8 (California)',
    removalOrderId: 'REM-2026-0881-LGB8',
    status: 'LIQUIDATED',
    grade: 'GRADE_B_LIQUIDATE',
    inspectionNotes: 'Khách khiếu nại hộp bị nứt nắp nhựa khi nhận. Đã thanh lý theo lô cho đối tác buôn sỉ tại Los Angeles thu hồi 55% giá trị vốn.',
    estimatedValueRecoveryUsd: 420,
    relabelCostUsd: 0,
    updatedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'rev-03',
    clientId: 'client-lotus-03',
    sku: 'VN-COCONUT-SPOON-SET6',
    asin: 'B0C9DEF456',
    title: 'Bộ Thìa Muỗng Gỗ Dừa Bến Tre Thủ Công Mỹ Nghệ (Set 6)',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300',
    unitsReturned: 15,
    returnReason: 'DAMAGED_IN_TRANSIT',
    fbaWarehouseOrigin: 'LAX9 (California)',
    removalOrderId: 'REM-2026-0810-LAX9',
    status: 'RE_INJECTED_FBA',
    grade: 'GRADE_A_NEW',
    inspectionNotes: 'Đã hoàn tất dán tem Barcode FNSKU mới và đóng pallet 150 bộ châm ngược lại kho ONT8.',
    estimatedValueRecoveryUsd: 285,
    relabelCostUsd: 5.25,
    recycledIntoFbaShipmentId: 'FBA18-INJ-VNSPOO-8819',
    updatedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
]

export const mockDemurrageRecords: DemurrageTrackingRecord[] = [
  {
    id: 'dem-01',
    clientId: 'client-vina-01',
    containerNumber: 'TCLU8892104',
    billOfLading: 'KRY-VNM-LAX-8801',
    vesselName: 'Ever Given / V.042W',
    arrivalPort: 'Port of Long Beach (LGB)',
    dischargeTimestamp: new Date(Date.now() - 42 * 3600000).toISOString(),
    lastFreeDayTimestamp: new Date(Date.now() + 54 * 3600000).toISOString(),
    freeDaysAllowed: 4,
    remainingFreeHours: 54,
    estimatedDemurrageFeePerDay: 225,
    riskLevel: 'WARNING',
    drayageAssignedTrucker: 'Pacific Drayage Logistics LLC (Driver: David Nguyen)',
    truckerPhone: '+1 (562) 890-1122',
    gateOutStatus: 'DRAYAGE_EN_ROUTE',
    iorModel: 'DDP_FORWARDER',
  },
  {
    id: 'dem-02',
    clientId: 'client-anan-02',
    containerNumber: 'MSKU4120982',
    billOfLading: 'FLX-VNM-LAX-4419',
    vesselName: 'Maersk Mc-Kinney Moller / V.102E',
    arrivalPort: 'Port of Los Angeles (LAX Pier 400)',
    dischargeTimestamp: new Date(Date.now() - 12 * 3600000).toISOString(),
    lastFreeDayTimestamp: new Date(Date.now() + 84 * 3600000).toISOString(),
    freeDaysAllowed: 5,
    remainingFreeHours: 84,
    estimatedDemurrageFeePerDay: 275,
    riskLevel: 'SAFE',
    drayageAssignedTrucker: 'California Fast Freight Trucking',
    truckerPhone: '+1 (310) 745-9988',
    gateOutStatus: 'READY_FOR_PICKUP',
    iorModel: 'FOREIGN_IOR_BOND',
  },
]

export const mockFbaCapacityUsages: FbaCapacityUsage[] = [
  {
    id: 'cap-01',
    clientId: 'client-vina-01',
    storageType: 'STANDARD_SIZE',
    currentUsageCubicFeet: 1240,
    monthlyLimitCubicFeet: 1500,
    utilizationPercentage: 82.6,
    nextMonthEstimatedLimitCubicFeet: 1650,
    biddingStatus: 'BID_SUBMITTED',
    requestedExtraCubicFeet: 450,
    bidPricePerCubicFeet: 0.15,
    estimatedReservationFeeUsd: 67.5,
    performanceCreditEligible: true,
  },
  {
    id: 'cap-02',
    clientId: 'client-lotus-03',
    storageType: 'OVERSIZE',
    currentUsageCubicFeet: 310,
    monthlyLimitCubicFeet: 400,
    utilizationPercentage: 77.5,
    nextMonthEstimatedLimitCubicFeet: 420,
    biddingStatus: 'NO_BID',
    performanceCreditEligible: true,
  },
]

export const mockEtaDeviationAlerts: EtaDeviationAlert[] = [
  {
    id: 'eta-alert-01',
    shipmentId: 'VXM-SHP-2026-001',
    trackingNumber: 'KRY-VNM-LAX-8801',
    carrierName: 'Kerry Ocean LCL',
    vesselName: 'CMA CGM Palais Royal',
    originalEta: '15/09/2026',
    updatedEta: '19/09/2026',
    deviationDays: 4,
    affectedSkus: ['VN-COCOA-ORGANIC-500G'],
    automaticActionTriggered: 'PPC_THROTTLED_30',
    status: 'ACTIVE_INTERVENTION',
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
]

export const mockSpApiQueueStatus: SpApiQueueStatus[] = [
  {
    endpoint: '/fba/inbound/v0/shipments',
    currentRateLimitPerSec: 2.0,
    activeQueueLength: 0,
    tokenBucketCapacity: 30,
    retryCount24h: 3,
    backoffAverageSeconds: 1.8,
    offlineCacheStatus: 'READY',
    lastSyncTimestamp: new Date().toISOString(),
  },
  {
    endpoint: '/orders/v0/orders',
    currentRateLimitPerSec: 0.0167,
    activeQueueLength: 1,
    tokenBucketCapacity: 20,
    retryCount24h: 1,
    backoffAverageSeconds: 4.2,
    offlineCacheStatus: 'READY',
    lastSyncTimestamp: new Date().toISOString(),
  },
]

// ====================================================================
// SPRINT 3.1 — PLACEMENT METRICS DEMO (SIMULATED MODE CHO PLACEMENT ENGINE)
// Số liệu đặt tên campaign khớp mockPpcCampaigns để UI demo tính năng
// Placement Optimization (Top of Search vs Product Pages).
// ====================================================================
export const mockPlacementMetrics: {
  campaignName: string
  placement: 'TOP_OF_SEARCH' | 'PRODUCT_PAGES' | 'REST_OF_SEARCH'
  impressions: number
  clicks: number
  spend: number
  sales: number
  orders: number
  currentBoostPct: number
}[] = [
  // Campaign 1: ToS hiệu quả vượt trội -> engine sẽ đề xuất BOOST_UP
  { campaignName: 'SP - Dark Chocolate - Broad', placement: 'TOP_OF_SEARCH', impressions: 18420, clicks: 412, spend: 618.00, sales: 2736.40, orders: 68, currentBoostPct: 25 },
  { campaignName: 'SP - Dark Chocolate - Broad', placement: 'PRODUCT_PAGES', impressions: 22150, clicks: 388, spend: 542.10, sales: 1084.20, orders: 31, currentBoostPct: 0 },
  { campaignName: 'SP - Dark Chocolate - Broad', placement: 'REST_OF_SEARCH', impressions: 9320, clicks: 142, spend: 198.80, sales: 496.99, orders: 14, currentBoostPct: 0 },
  // Campaign 2: ToS ăn tiền (ACOS vượt 1.5x target 25%) -> BOOST_DOWN về 0
  { campaignName: 'SP - Cocoa Powder - Broad Scale', placement: 'TOP_OF_SEARCH', impressions: 12780, clicks: 296, spend: 592.00, sales: 355.20, orders: 7, currentBoostPct: 40 },
  { campaignName: 'SP - Cocoa Powder - Broad Scale', placement: 'PRODUCT_PAGES', impressions: 15420, clicks: 244, spend: 390.40, sales: 1042.90, orders: 26, currentBoostPct: 0 },
  { campaignName: 'SP - Cocoa Powder - Broad Scale', placement: 'REST_OF_SEARCH', impressions: 6890, clicks: 98, spend: 147.00, sales: 294.00, orders: 7, currentBoostPct: 0 },
  // Campaign 3: ToS ổn định -> HOLD
  { campaignName: 'SP - Agarwood Incense - Exact Defense', placement: 'TOP_OF_SEARCH', impressions: 8210, clicks: 186, spend: 279.00, sales: 1302.00, orders: 33, currentBoostPct: 15 },
  { campaignName: 'SP - Agarwood Incense - Exact Defense', placement: 'PRODUCT_PAGES', impressions: 11440, clicks: 172, spend: 258.00, sales: 948.60, orders: 24, currentBoostPct: 0 },
  { campaignName: 'SP - Agarwood Incense - Exact Defense', placement: 'REST_OF_SEARCH', impressions: 4320, clicks: 64, spend: 92.80, sales: 231.99, orders: 6, currentBoostPct: 0 },
]
